source/docs/migration.md

The instructions on the Hexo docs site will match the instructions for the WordPress plugin more closely.

Improve WordPress migrate instructions

---

source/_data/plugins.yml

Adds a Stylus renderer plugin with support for Axis, jeet, Nib, Rupture and Sourcemaps.

Add `hexo-renderer-yasr`

---

source/docs/variables.md

Added the `published` variable to the `post` layout.
Should the ellipsis on line 27 be removed? What else would be an article?

Add docs on published variable

---

.gitignore
source/_data/plugins.yml

Plugin link: [hexo-toc](https://github.com/bubkoo/hexo-toc)
Insert a markdown TOC(Table Of Content) before posts be rendered. 
Unlike the native [`toc`](http://hexo.io/docs/helpers.html#toc) helper, this plugin will inject a TOC only when a placeholder(``) found in the raw markdown files. And the TOC will be injected after the placeholder. 
All you need to do is placing a placeholder(``) in your post when and where needed. 
**Note:** this plugin will not mangle your posts(markdown files), so you can use it bold.

add hexo-toc plugin

---

source/_data/plugins.yml

Plugin link: [hexo-migrator-github-issue](https://github.com/Yikun/hexo-migrator-github-issue).
The plugin can migrate your blog from Github issue to Hexo.

Add Hexo-Migrator-Github-Issue plugin.

---

source/_data/plugins.yml

Hello,
I'd like to add my plugin to the Hexo plugins list.
The plugin is called `hexo-front-matter-excerpt` and it allows writing post excerpts in the yaml front-matter of a post.

Add hexo-front-matter-excerpt to Hexo official plugins list

---

source/_data/plugins.yml

**hexo-github**
Display a GitHub repositoy badge with timeline in your post to keep track of version difference.
https://github.com/akfish/hexo-github

Add hexo-github tag plugin

---

source/_data/plugins.yml

"The google maps tag plugin for hexo is designed to be a way to add simple maps to your hexo site. The main tag, called googlemaps requires an endtag called endgooglemaps"

added the hexo-tag-googlemaps plugin to the plugin list

---

source/_data/plugins.yml

Similar to the Spotify widget plugin but for the Deezer service. Example of it working is given on the plugin repo.

Adding the hexo-tag-deezer music widget plugin

---

source/_data/plugins.yml

Compress CSS with [more-css](https://github.com/army8735/more). This is an alternative for [hexo-clean-css](https://github.com/hexojs/hexo-clean-css), with better results in some cases, see the [CSS minification benchmark](https://goalsmashers.github.io/css-minification-benchmark/).

Added hexo-more-css.

---

source/_data/plugins.yml

Add hexo-generator-seo-friendly-sitemap plugin:
SEO friendly sitemap generator for Hexo. Generate separated sitemap files for pages, posts, categories, tags and add a XSL stylesheet.

Add SEO Friendly Sitemap Generator Plugin

---

source/_data/plugins.yml

Generate search data for Hexo 3.0.This plugin is used to generator a search.xml file.The file contains the main data of your blog so that you can use the data to finish a search function for your blog.

Add search.xml generator.

---

source/docs/configuration.md

When I first read this on the website I was confused by the overload of data from the [timezone][1] option and lack of info on the language option.
I added a Wikipedia link to the proper two digit language codes and the [default][2] of `en`.
[1]: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
[2]: https://github.com/hexojs/hexo/blob/f01a9aa3db9dc5b52d056c7467186fa5f33c5857/test/scripts/filters/i18n_locals.js#L12-L13

Clarify expected format of config values

---

source/_data/plugins.yml

I created a plugin to generate a JSON file with contents of pages and posts and some site meta data.
I think it's useful for AJAX search or API content. So I added it to the site plugins list.

Add hexo-generator-json-content to plugins list

---

source/docs/helpers.md

Makes it known that an object of keys can be passed into the Gravatar helper so other parameters such as a default image can be used.

Clarify Gravatar helper documentation

---

source/docs/asset-folders.md
source/docs/data-files.md
source/docs/deployment.md
source/docs/front-matter.md
source/docs/generating.md
source/docs/helpers.md
source/docs/internationalization.md
source/docs/permalinks.md
source/docs/plugins.md
source/docs/server.md
source/docs/tag-plugins.md
source/docs/templates.md
source/docs/themes.md
source/docs/troubleshooting.md
source/docs/writing.md

I read through the docs and edited them as I went along.
There was an issue with showing off the triple backtick code in the tag-plugins.md file, causing it to error out. I changed it so at least the syntax is shown now, but it's still not looking great since the engine processes any appearance of triple backticks (even in a code block or a raw tag).

Edited docs for spelling and grammar

---

source/_data/plugins.yml

This is a simple plugin that adds a `hexo edit` command to view and open posts from the command line.
(also fixed a typo in another plugin's description)

added hexo-easy-edit plugin

---

source/_data/plugins.yml

Hi, I add a plug-in to fix the spacing problem of CJK lines in markdown parsing:
```
.....中文结尾
中文顶格...
will result in
.....中文结尾 中文顶格...
`- note the space here
```
This plug-in will fix that.

add plugin: hexo-filter-fix-cjk-spacing

---

source/docs/helpers.md

Hi, I (and it seems [others](https://github.com/hexojs/hexo/issues/408)) have been confused by the fact that you can't use helper functions in source files.  I think it might be helpful to state this explicitly.  I'm also curious why this is the case.

Clarify that helpers can't be used in source files

---

source/_data/plugins.yml

Created a new plugin to support LaTeX. This uses the katex library from Khan Academy.
This can be used to insert math equations and formulas.

Add link to hexo-tag-katex plugin

---

source/_data/plugins.yml

updated the hexo-tag-githubimage to support Hexo V3.x.

add hexo-tag-githubimage plugin to plugins list

---

source/_data/plugins.yml

I created this trio of tools to aid in offloading image processing tasks on the service-provider imgix, which has a great, full-featured API and is cheap. I think it makes a great compliment to a simple static site where more control over images is needed.
Briefly:
* the **tag** {% imgix %} is a slightly modified version of the native Hexo {% img %} tag, supporting imgix api params and doing domain replacement for applicable paths / urls.
* the **helper** does the heavy lifting for the above process, and is exposed in templates for use there
* the **filter** registers with the before_render hook to parse out markdown-defined images, apply imgix domains to them, and optionally will apply configured params and / or sizing data (specified through the proposed markdown extension).

adding hexo-imgix plugin to plugins list

---

source/_data/plugins.yml

I wrote a plugin these days to add 'indicate the source' informations to posts without hurting readers' reading experience.
Visit my blog for more detail.
https://blog.jamespan.me/2016/01/15/do-not-forget-to-indicate-the-source/

add plugin hexo-filter-indicate-the-source

---

source/docs/configuration.md

minimatch is used by glob, but there's no indication they'll have the same defaults etc. without examples, this is a confusing link.

Correct library used

---

source/_data/plugins.yml

Adds reference information for the hexo-tag-imgurgal tag plugin that can be found here: https://github.com/DrummerHead/hexo-tag-imgurgal
Cheers!

Add hexo-tag-imgurgal information

---

source/docs/plugins.md

Ran into this today, I from reading the docs I thought hexo would detect my plugin from the file system, adding this line to the docs clarifies things.

update docs, include your plugin in package.json

---

source/_data/plugins.yml

Hi,
I created a [plugin](https://github.com/Gisonrg/hexo-github-card) that can show GitHub user and repo information. Please help to add to the site :smile: 
Thank you!

Add hexo-github-card plugin

---

source/_data/plugins.yml

I created a plugin that converts all URLs and emails to HTML links.
Various options available to also convert phone numbers, twitter handles and hashtags + possibility to add custom classes.
Thanks

Add hexo-autolinker plugin

---

source/_data/plugins.yml

A plugin to support markdown footnotes in your Hexo blog posts

add hexo-footnotes plugin

---

source/_data/plugins.yml

let template can refer the image url set in post markdown, it's useful in case like, you want to set a cover image for each blog post, and serve the image by image cloud server.

added hexo-url-image plugin

---

source/_data/plugins.yml

Fix the i18n typed wrong to 118n issue

Fix the wrong name of hexo-generator-i18n

---

source/_data/plugins.yml

I created a new plugin: `hexo-generator-json-feed`.
It's similar to my other plugin `hexo-generator-json-content`, but generates a JSON file only for posts with objects like a RSS feed channel structure.

Add new plugin to list: hexo-generator-json-feed

---

source/docs/variables.md

`page.total` in **HOME(index)** means total number of **pages** not posts

Fix typo in docs/variables.md

---

source/docs/configuration.md

Default date format appears to be YYYY-MM-DD when I installed.

Minor documetation correction

---

source/docs/themes.md

Link to Swig pointed to a 404 page, fixed that.

Fix dead link

---

source/zh-cn/docs/helpers.md

Line: 556
is `&hellip` not `&hellp`
`&hellip` means horizontal ellipsis and is used to denote ... (i.e. three dots).

Correct wrong spell

---

source/docs/troubleshooting.md

Several recent issues (e.g. https://github.com/hexojs/hexo/issues/2087, https://github.com/hexojs/hexo/issues/2013) are about a `$ hexo server` error:
```
Error: watch EPERM
```
It is a result of trying to use a filesystem watcher in a BashOnWindows environment, something that is currently unsupported by WSL. I added an explanation and workaround to the troubleshooting page.

added EPERM error on WSL to Troubleshooting

---

source/_data/plugins.yml

Added to the plugin list.
Plugin lets you embed upload videos in your asset_path or elsewhere on the server.
Install:
npm i hexo-tag-html5video
Usage: 
With no args, the defaults are used: width = '100%' height = '250px' codec = 'video/webm'
{% html5video %} {% asset_path big-buck-bunny_trailer.webm %} {% endhtml5video %}
or with args:
{% html5video '100%' '250px' 'video/mp4' %} {% asset_path big-buck-bunny_trailer.webm %} {% endhtml5video %}

Adding hexo-tag-html5video to plugin list

---

source/api/generator.md

The archive page example should have `data: locals` instead of `data: locals.posts` or an error will occur.
Test on: hexo: 3.2.2
Test script and versions documented @ https://gist.github.com/7ef9b57152f241d2421c5d1b9355a1da

api: generator: Update data for archive generator

---

source/_data/plugins.yml

A workflow plugin that leverages the Google Drive API for pulling `text/markdown` files from Google Drive. To and from folders are configurable. Any feedback you can provide would be greatly appreciated

hexo-sync-plugin for retrieving posts and drafts from Google Drive

---

source/_data/themes.yml

现在是这样的：  #c #l #e #a #n   
应该是这样的： #clean

Hexo官网 Theme下标签被转成了单个字符 已修复

---

README.md
netlify.toml

I added a deploy to Netlify button to the README. Feel free to test it out below. The toml file just tells Netlify that your index.html is in the root and your build command is `hexo generate`. I did this, because I want to add a hexo example to http://www.staticgen.com/ and this would help.
Netlify also has a liberal [Open Source](https://netlify.com/open-source) plan for all open source projects, in case you had some other hexo examples you would like to host there. 
[![Deploy to Netlify](https://www.netlify.com/img/deploy/button.svg)](https://app.netlify.com/start/deploy?repository=https://github.com/bdougie/site)
Let me know if you have questions.

Add deploy to Netlify Context to README

---

source/_data/plugins.yml

This plugin lets you generate multiple sizes of each image in your `source` directory; for example, thumbnails and gallery images.

Add hexo-image-sizes plugin

---

source/_data/plugins.yml

This pull request is simply to add a plugin to the Hexo website. 
The plugin is a template helper, which can add images from an Instagram account to the website.

Add hexo-instagram-wall to plugin registry

---

source/_data/plugins.yml

Added `hexo-helper-htmlentities` plugin to encode html entities using [node-html-entities](https://github.com/mdevils/node-html-entities).

Add plugin hexo-helper-htmlentities

---

themes/navy/layout/partial/after_footer.swig
themes/navy/source/css/_partial/base.styl
themes/navy/source/css/_partial/mobile_nav.styl
themes/navy/source/js/scrollingelement.js
themes/navy/source/js/toc.js

Try to support [FireGestures](https://github.com/gomita/firegestures/) (Firefox) and similar gesture extensions in Google Chrome.
These browser extensions/addons maybe(**not** confirmed) modify `body.scrollTop` or `html.scrollTop` when scrolling gestures are triggered. Using other element as the scrolling element will fail these gestures.
However `document.scrollingElement` is experimental, and not all browsers support it(See [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/scrollingElement)).  Polyfill (IE 11 tested) was taken from [scrollingelement.js](https://mths.be/scrollingelement).

Using document.scrollingElement in toc.js

---

source/_data/plugins.yml

Add plugin hexo-directory-category
Automatically add category to Hexo article according to the article file directory.

Add plugin hexo-directory-category

---

themes/navy/source/css/_partial/base.styl

Fixes #448 
`position: relative` on body is redundant, as without positioned ancestor the absolute element is positioned relative to html anyway.
P.S.
I also tried bringing the `mobile-nav-toggle` in front of the dimmer, as it looks like it was intended to be on top. But it is not possible with css alone, as its parent `#container` has a [transform](https://www.w3.org/TR/css-transforms-1/#module-interactions) on it, which creates a [stacking context](https://philipwalton.com/articles/what-no-one-told-you-about-z-index/). Meaning the container and hamburger button are grouped together and can only be either both on top of the dimmer or both below.
I know it isn't a breaking bug. But still it would be nice to fix it.

Fix horisontal scrolling

---

source/_data/plugins.yml

Adds [hexo-generator-json-feed-org](https://github.com/rmlewisuk/hexo-generator-json-feed-org), a plugin to generate a valid [jsonfeed.org](http://jsonfeed.org) feed.
Note: this is distinctly different from https://github.com/alexbruno/hexo-generator-json-feed as that is more of a general purpose JSON/API endpoint.
Was discussed in https://github.com/hexojs/hexo-generator-feed/issues/55, linking here for the sake of completeness.

Add hexo-generator-json-feed-org to plugins list

---

source/docs/contributing.md
source/ko/docs/contributing.md
source/ru/docs/contributing.md
source/zh-tw/docs/contributing.md

The original guide page (https://google.github.io/styleguide/javascriptguide.xml) shows:
"Please note: there's a newer version of this guide that includes ECMAScript 6th Edition features. It lives here (https://google.github.io/styleguide/jsguide.html)."

Update Google JavaScript Style Guide Url

---

source/zh-tw/api/filter.md
source/zh-tw/docs/commands.md
source/zh-tw/docs/configuration.md
source/zh-tw/docs/index.md
source/zh-tw/docs/migration.md
source/zh-tw/docs/setup.md

Fix internal link that still having wrong prefix "docs/" in zh-tw docs.
Let zh-tw docs match en docs in the range of "Getting Started".

Fix internal link & let zh-tw docs match en docs in the range of "Getting Started"

---

source/_data/plugins.yml

the hexo blog post url is displayed as a number

adding hexo-number-title plugins

---

themes/navy/source/css/_partial/mobile_nav.styl

Don't know why `overflow-x: hidden` in #449 doesn't work on iOS Safari, so problem #448 still not solved. I tried to move `width: 100%` from `#mobile-nav-dimmer` to `.mobile-nav-on:#mobile-nav-dimmer`, worked fine on me.
Can anyone have a check on this? I don't have much experience on css, hope not to cause another problem, thanks ;)

Fix horisontal scroll

---

source/_data/plugins.yml

```
{% rtl %}
مقتطفات من بعض الحكم
{% endrtl %}
“A small leak will sink a great ship.” - Benjamin Franklin
{% rtl %}
"لو أنك عشتَ في الماضي و تصرفت كأنك في الماضي ، سوف يكون صعباً على المُستقبلِ أن يراكَ." - Body of Lies
{% endrtl %}
```
which results in
```
مقتطفات من بعض الحكم
{% ltr %}
“A small leak will sink a great ship.” - Benjamin Franklin
{% endltr %}
"لو أنك عشتَ في الماضي و تصرفت كأنك في الماضي ، سوف يكون صعباً على المُستقبلِ أن يراكَ." - Body of Lies
```
that results in

adding rtl and ltr tag plugins

---

source/_data/themes.yml

sorry for this, but the theme screenshot was not showing on Hexo Thems page.
the screenshot name must be _exactly_ like theme name in the yml.

theme renamed to match its lowercased screenshot

---

source/_data/plugins.yml

The Hexo plugin publish your posts to GitHub issues.

add new plugin hexo-generator-issues

---

source/_data/plugins.yml

I developed a new plugin.
This plugin can push the picture inside posts to Alicloud OSS, in order to cooperate with  Alicloud CDN accelerate the site.
plugin: https://github.com/chenxuefei-pp/hexo-tag-ossimg

add plugin hexo-tag-ossimg

---

source/_data/plugins.yml

Add the hexo-deployer-cos plugin, COS is a  Object Storage platform from Tencent. You can used the plugin to deploy your Hexo blog to COS.

add the hexo-deployer-cos plugins

---

source/_data/plugins.yml

Add a new plugin called Hexo-light-gallery.

add plugin, Hexo-light-gallery

---

source/_data/plugins.yml

Add `hexo-pwa` plugin.
`hexo-pwa` let Hexo sites have these two capabilities:
- Web App Manifest - Users can add your site to mobile home screen
- Service Worker - Make your site available offline
[https://github.com/lavas-project/hexo-pwa](https://github.com/lavas-project/hexo-pwa)

add hexo-pwa plugin

---

source/docs/tag-plugins.md

I've added information about the `` in the tag plugins section of the site. Technically, it's not a tag plugin, however this place looked the most suitable for me.
Fixes hexojs/hexo#2652.

Add info about <!-- more --> to the docs

---

source/_data/plugins.yml

It's hexo tag plugin that shows text hint above post body. I created it in the last few days.

Add a new hexo plugin: hexo-tag-hint😊

---

source/api/generator.md

`/archives/index.html/index.html`,
or in pretty format, `/archives/index.html/`.
tested with hexo-pagination 0.0.2.

Fix pagination example. It would have made a route for

---

source/_data/plugins.yml

published my tippy plugin -- pandoc edition. Renamed the previous edition to hexo-markdown-it-tippy to clear distinguish the two.

Update  plugins.yml

---

source/docs/configuration.md

The `theme_config` setting, for configuring themes in the primary `_config.yml` file is extremely useful.
It doesn't appear in the documentation, so this commit adds it.
The example code is taken directly from the original pull request: https://github.com/hexojs/hexo/pull/757

Documentation for the 'theme_config' setting

---

source/_data/plugins.yml

Add hexo-migrator-gists plugin. (GithubGist migrator plugin for Hexo)

Add hexo-migrator-gists plugin

---

source/_data/plugins.yml

There are some plugins like this already but I think this one is worth adding because it's:
- not depending on ImageMagick being installed
- integrated with the routing, so it can be used with other plugins (like image minification)
- lazy for `hexo server` - it resizes images only if requested
- covered by specs
- owned by hexojs organization

Add hexo-filter-responsive-images plugin

---

source/_data/plugins.yml

It has been moved to the hexojs organization, so the repo URL has changed as well.

Update hexo-fontawesome plugin URL

---

source/_data/plugins.yml

add [hexo-tag-link-preview](https://github.com/minamo173/hexo-tag-link-preview) plugin on Hexo site.

add a new hexo plugin: hexo-tag-link-preview

---

source/_data/plugins.yml

add `hexo-auto-category` to Plugin list
https://github.com/xu-song/hexo-auto-category
A Hexo plugin, which generates categories automatically from folder structure for each post.

add plugin hexo-auto-category

---

source/_data/plugins.yml

This is a plugin requires an extra integration with a theme, so it's intended for theme authors. For now it only generates low-quality SVGs using potrace, but there is more to come soon-ish.
Inspired by [Using SVG as placeholders ](https://jmperezperez.com/svg-placeholders/)

Add hexo-filter-lqip

---

source/_data/plugins.yml

Generate zip search data for Hexo 3.0. This plugin is used for generating a search index file, which contains all the neccessary data of your articles that you can use to write a local search engine for your blog.

Add hexo-generator-search-zip plugin

---

source/_data/plugins.yml

This PR adds my plugin, `hexo-tag-autogallery` to the lists of available plugins.
`hexo-tag-autogallery` is a tag plugin that generates automatically photo gallery from contents of provided directory and using given template.
https://www.npmjs.com/package/hexo-tag-autogallery

Add plugin: hexo-tag-autogallery

---

source/_data/themes.yml

I'm the author of theme "beautiful-hexo". Since my custom domain no longer points to github.io, here is the fix.

Fix broken theme preview link

---

source/_data/plugins.yml

Simply added a new plugin to the plugin list.
This plugin let you embed a Garmin connect activity in your hexo blog.

hexo-tag-garminconnect plugin added

---

source/_data/plugins.yml

**hexo-undraft** provides a better publish experience via cli.
It basically does `mv` command like in the Terminal, but will prompt up and let you choose which one to mv. It will find your posts you want to publish first, then let you select the post you really want to publish and lastly move the post to your customized folder. That easy! Vice versa too.
`npm install --save hexo-undraft`
**in posts you write, add a setting called "dest" on the top. If you omit this setting, the plugin will use `<hexo_folder>/source/_posts` as the default path.**
example:
```
---
title: example is here
tags:
dest: _posts/foo/bar
---
```
`hexo undraft [title] [-t | --to FOLDER] [-a | --all]`
* title: input full or partial title to let it find posts that you want to publish
* -t | --to FOLDER: if you give …

better experience publishing via cli

---

source/docs/troubleshooting.md
source/docs/variables.md
source/ko/docs/troubleshooting.md
source/pt-br/docs/troubleshooting.md
source/pt-br/docs/variables.md
source/ru/docs/troubleshooting.md
source/zh-cn/docs/troubleshooting.md
source/zh-tw/docs/troubleshooting.md

* DataModel link (https://hexo.io/warehouse/) is broken.
* And update warehouse repository link.

Fix link to warehouse repository and doc

---

source/_posts/2018-10-19-hexo-3-8-released.md

[Official page news](https://hexo.io/news/)  is no longer update.
Hexo does not seem to be updated from the users. It is not good.
I wrote 3.8.0 release note.
It only copy from [hexo main repository](https://github.com/hexojs/hexo/releases/tag/3.8.0). Not write detail. But, better than nothing.
Of course I already checked work well on my local machine.

3.8.0 release note

---

source/_data/plugins.yml

This pull adds new plugins to the catalog, [hexo-yam](https://github.com/weyusi/hexo-yam) and [hexo-nofollow](https://github.com/weyusi/hexo-nofollow).
hexo-yam: Minify and compress html, js and css. Support gzip and brotli compressions.
hexo-nofollow: Adds nofollow attribute to all external links in posts. A more updated version of [hexo-autonofollow](https://github.com/liuzc/hexo-autonofollow).

Add plugins: hexo-yam and hexo-nofollow

---

source/docs/tag-plugins.md

The title in front matter (or post.title) is not necessarily similar to the filename of the post. The difference could occur when user prefers to create a post manually, instead of `$ hexo new [layout] <title>`.
I also replaced `slug` with more common `filename`.
1. Using post title:
```
{% post_path old-post-is-ancient %}
Testing a <a href="{% post_path old-post-is-ancient %}">link</a>.
{% post_link old-post-is-ancient %}
```
rendered as:
```html
<p>Testing a <a href="">link</a>.</p>
```
https://github.com/weyusi/hexo-testing/blob/9bbd4643ab7149f516d20293c77574d56c0efc0e/2018/11/01/test-post/index.html#L77-L79
2. Using file name:
```
{% post_path old-post %}
Testing a <a href="{% post_path old-post %}">link</a>.
{% post_link old-post %}
```
rendered as:
```html …
```

post_path and post_link use filename not post.title

---

README.md

Delete link to [hexojs/hexojs.github.io](https://github.com/hexojs/hexojs.github.io) in README.
The [hexojs/hexojs.github.io](https://github.com/hexojs/hexojs.github.io) has already not update after migrate to Netlify.

chore(doc): delete link to hexojs.github.io

---

package.json

suggested by https://github.com/hexojs/site/pull/796#issuecomment-433789961
this pull will only affect new images, current ones have been compressed (https://github.com/hexojs/site/pull/796).

chore: compress images upon commit

---

gulpfile.js

gulp.useRef.assets is no longer used

---

themes/navy/layout/partial/after_footer.swig

And triggers a warning when browsing https://hexo.io/plugins/

Lunr does not match version in package.json

---

yarn.lock

Currently travis ci has error because `npm run build` command failed caused by gulp dependency

chore(package): update dependencies (#844)

---

source/_data/plugins.yml

---
Yet another permalink plugin that exploits [ai/nanoid](https://github.com/ai/nanoid) to generate abbreviated post links.
The plugin provides configurable character set and ID length and performs ID validation and uniqueness check before route generation and while creating new post via `hexo new`.

chore(plugin): add hexo-nanoid plugin.

---

gulpfile.js

@hexojs/core 
IMHO, this issue is high priority issue. Could you please review & merge this?
Hexo official site [themes](https://hexo.io/themes/) preview images can not see.
In html src image link extension is `jpg`. But, acturally (generated by gulp) image extension is `jpeg`. Please see below two images. 
Btw, I believe this issue caused by dependency package version. I propose include `package-lock.json`
Thanks

fix: generated image link jpg to jpeg

---

source/_data/themes.yml

From https://github.com/hexojs/hexo/issues/3520 issue.
I updated link of theme.

fix(theme): change link of Raytaylorism themes

---

source/docs/configuration.md

also mention skip_render can be used to exclude posts.
Recommend user to enclose value with quotes, as a respond to https://github.com/hexojs/hexo/issues/3306 https://github.com/hexojs/hexo/issues/3516.

docs: add more examples to include/exclude

---

source/_data/plugins.yml

A Hexo plugin that generates a qrcode image and inserts it into a post.

Add hexo-tag-qrcode plugin

---

source/_posts/2019-05-22-hexo-renderer-marked-1-0-0_1_0_1-released.md

Please see [v1.0.0](https://github.com/hexojs/hexo-renderer-marked/releases/tag/1.0.0) & [v1.0.1](https://github.com/hexojs/hexo-renderer-marked/releases/tag/1.0.1)

chore(news): create hexo-renderer-marked 1.0.0 & 1.0.1 released news

---

gulpfile.js
package.json

Closes #839 ?
Previous execution chain:
```
default
useref
screenshot
screenshot
rev
clean
resize
rev
revreplace
rev
```
The order is reversed (sort of) in Gulp@4.
https://fettblog.eu/gulp-4-parallel-and-series/

chore(gulp): upgrade to v4

---

package.json
source/_posts/2019-06-19-hexo-3-9-released.md

Based on release note of https://github.com/hexojs/hexo/releases/tag/3.9.0 .

Hexo 3.9.0

---

source/docs/helpers.md
source/ko/docs/helpers.md
source/pt-br/docs/helpers.md
source/ru/docs/helpers.md
source/th/docs/helpers.md
source/zh-cn/docs/helpers.md
source/zh-tw/docs/helpers.md

- Update gravatar helper example as the output is now https ([reference](https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/gravatar.js#L15)).
- Add a missing gravatar helper usage for `zh-tw`

Fix gravatar helper related

---

source/docs/helpers.md

I only found out how to use it through the [test script](https://github.com/hexojs/hexo/blob/7fba3c1f667f8beb331f16776f1c7c6908d78c3c/test/scripts/helpers/list_categories.js#L215-L217)
It would be helpful in docs.

docs: add examples of transform() in List helpers

---

source/docs/tag-plugins.md

img tag works with single quotes and double quotes.  It does not currently work with brackets.
https://github.com/hexojs/site/issues/960

Update img tag documentation

---

source/docs/configuration.md

this applies primarily for `zh`. I noticed many themes ship with `zh-tw` or `zh-hk`, so user is not actually confined just 2-letter ISO code. The value still has to begin with ISO codes.

docs: optional language variant

---

source/docs/index.md
source/zh-cn/docs/index.md

I have noticed some user comment at Hexo documents installation guide said they ran into trouble with `EACCES permissions errors` when execute `npm i hexo-cli -g`
npmjs has released a guide to solve that issue: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

docs: add a guide to fix EACCES permissions error

---

source/_data/plugins.yml

Hello,
I've created a new renderer for Hexo based on remark and rehype; may I integrate it into the plugin list?
The new renderer is very nice as it embed code highlighting, line numbering for codes, and math rendering by default with a simple configuration option; maybe some people would be interested ;) .

Adding a new Markdown renderer

---

source/api/helper.md
source/docs/helpers.md
source/ko/api/helper.md
source/ko/docs/helpers.md
source/pt-br/api/helper.md
source/pt-br/docs/helpers.md
source/ru/api/helper.md
source/ru/docs/helpers.md
source/th/api/helper.md
source/th/docs/helpers.md
source/zh-cn/api/helper.md
source/zh-cn/docs/helpers.md
source/zh-tw/api/helper.md
source/zh-tw/docs/helpers.md

[`js()`](https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/js.js) and [`css()`](https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/css.js) helpers no longer add type attribute, [nor necessary](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#JavaScript_types).

docs(helpers): type attribute is no longer added

---

source/docs/configuration.md

Address issue https://github.com/hexojs/hexo/issues/3688
WIP: I imagine the description for `highlight.tab_replace` is something like *Replace tab by n space, if the string is empty tabs won't be replaced* but I don't know it for sure.

highlight documentation

---

source/docs/helpers.md
source/ko/docs/helpers.md
source/pt-br/docs/helpers.md
source/ru/docs/helpers.md
source/th/docs/helpers.md
source/zh-cn/docs/helpers.md
source/zh-tw/docs/helpers.md

instead of `rel="external"`
https://github.com/hexojs/hexo/blob/f57f700fd768f1f400352ddf58a90d16bcf87a25/lib/plugins/helper/link_to.js#L17

docs(link_to): should be rel="noopener"

---

source/_data/sidebar.yml
source/docs/deployment.md
themes/navy/languages/en.yml

I'm writing github, gitlab pages and netlify guides which I intend to put them under Deployment section.
Personally I feel travis and gitlab ci are easier to use than 'hexo deploy' and integrate better with github and gitlab respectively. Even https://github.com/hexojs/warehouse uses travis to publish. 'hexo deploy' is more suitable for other platforms that lacks CI (or at least easy-to-use one).

docs: move Deployment to a separate section

---

source/_data/plugins.yml

I decided to [deprecate](https://github.com/curbengh/hexo-nofollow/issues/7) it in favor of [hexo-filter-nofollow](https://github.com/hexojs/hexo-filter-nofollow).

plugins: remove hexo-nofollow

---

source/docs/index.md

`stable` has been deprecated and currently alias as `node`, which install the latest Node (currently v12).

docs: update nvm syntax

---

themes/navy/layout/partial/share.swig

Noticed it while running [WebPageTest](https://webpagetest.org) on hexo.io
I can verify it has the same hash as https://buttons.github.io/buttons.js (v2.2.10).

fix(theme): load github button from jsdelivr

---

source/docs/one-command-deployment.md

I think there was confusion between the `hexo deploy` and `hexo generate`.
It sounds like we want to use `hexo generate` instead to build the project as seen in this PR: https://github.com/hexojs/hexo-starter/pull/21
I also add a one-click deployment button which links to https://zeit.co/new/hexo
Button Documentation: https://zeit.co/docs/v2/advanced/deploy-button

Update ZEIT Now deployment with script and button

---

source/docs/index.md

Since nvs is [recommended](https://github.com/hexojs/site/pull/1136) for most users, nvm guide is no longer relevant.
This also makes it appear more consistent with Git guide.
Linux guide doesn't include installing from official repo (e.g. `sudo apt-get install nodejs`) because Ubuntu 18.04 and Debian 9 (both LTS) still ship with Node 8.

docs(installation): simplify nodejs installation guide

---

_config.yml
package.json

A relic of the past [hexojs.github.io](https://github.com/hexojs/hexojs.github.io). It's not even necessary to use the config as example, as the [one-command deployment](https://hexo.io/docs/one-command-deployment) page already has the instruction.

build: remove unneeded hexo-deployer-git

---

scripts/responsive.js

`assetData` may have more than one element (resulted from multiple chunks), so `Array.join('')` should be used to avoid separator, instead of the default comma separator.

fix(responsive): join stream read properly

---

package.json
scripts/helpers.js

Emergency fix after #1139 as `full_url_for()` couldn't be found.
Netlify and Travis CI both don't have the latest commit when using `"hexojs/hexo"`
This PR force them to install the latest commit (https://github.com/hexojs/hexo/commit/79bdc9548752acfba89b26dec2c532c9346a1380)
Related issue: https://github.com/hexojs/site/pull/1102

fix: full_url_for helper not found

---

scripts/helpers.js

Another fix for https://github.com/hexojs/site/pull/1139
It's not very urgent because somehow the duplicated 'Next" is displayed on top of existing one, meaning it still display as one despite having two duplicate `<a>`.

fix(page_nav): remove duplicate 'Next' nav links

---

netlify.toml

I intend to harden HTTP security-related headers. I start with the easiest ones (least likely to cause breakage).
How to test:
1. Open deploy preview
2. Check the HTTP response header.
Ref: https://securityheaders.com/

fix(http-header): add x-frame and x-xss

---

package.json

Now that it's possible for us to clear the netlify's npm cache, this workaround is not needed anymore.
Workaround was initially introduced in https://github.com/hexojs/site/pull/1173 to fix https://github.com/hexojs/site/issues/1170. npm cache issue was first discovered in https://github.com/hexojs/site/pull/1102.
Remember to clear netlify cache immediately after merging this PR. I believe to merge this before merging the rest of [v4-related PRs](https://github.com/hexojs/site/milestone/1).

chore: always use latest commit of hexo

---

source/_posts/2019-10-10-hexo-4-released.md
source/_posts/2019-10-14-hexo-4-released.md

news: Hexo 4.0.0 released

---

netlify.toml

Netlify currently defaults to Node 8, this PR upgrades it to v10.
Set `production` environment to skip devDependency, eslint & imagemin are not relevant to netlify build.
ref: https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-and-javascript

build: use node 10 LTS and set prod env

---

.npmrc
source/docs/tag-plugins.md
source/ko/docs/tag-plugins.md
source/pt-br/docs/tag-plugins.md
source/ru/docs/tag-plugins.md
source/th/docs/tag-plugins.md
source/zh-cn/docs/tag-plugins.md
source/zh-tw/docs/tag-plugins.md

Closes #1098
Related https://github.com/hexojs/hexo/pull/3704

(#1098) Add docs about escape option in post_link & asset_link helpers

---

netlify.toml

[`nosniff`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Content-Type-Options) is to opt-out from [mime-type sniffing](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types#MIME_sniffing).
Feature-policy is mainly to prevent third-party resources to access device sensors, e.g. to mitigate possible [privacy risk](https://blog.lukaszolejnik.com/stealing-sensitive-browser-data-with-the-w3c-ambient-light-sensor-api/). This header is highly experimental, so some of the directives are not supported in certain browsers.
ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Feature-Policy

site(http_header): add nosniff and feature-policy

---

themes/navy/layout/index.swig

Fix 404 theme link for other languages.
When at subdirectory of other languages (for example `https://hexo.io/zh-cn/`), `themes/` will turn into something like `/zh-cn/themes/` and causes 404.

fix(index): theme link 404

---

source/docs/tag-plugins.md
source/ko/docs/tag-plugins.md
source/pt-br/docs/tag-plugins.md
source/ru/docs/tag-plugins.md
source/th/docs/tag-plugins.md
source/zh-cn/docs/tag-plugins.md
source/zh-tw/docs/tag-plugins.md

`filename` is more common, compared to `slug`.

docs: replace 'slug' term with 'filename'

---

scripts/helpers.js

Fixed #1210 
This PR hide 'undefined', but the sidebar element exists. Please see the following. 
We have to add a conditional operator to [here](https://github.com/hexojs/site/blob/22784f5c06cb48eea3d4e0620b5b27725a9b7e74/themes/navy/layout/page.swig#L32), if we do not want render sidebar element when it does not exists.

fix: 'undefined' on about page (#1210)

---

_config.yml

Noticed when testing https://github.com/hexojs/site/pull/1225. Netlify prettify the urls by default, so this config makes it more consistent.
the sitemap still have url like `hexo.io/docs/configuration.html`, where it should be `hexo.io/docs/configuration/`. `pretty_urls.trailing_html` option is not available yet.

build: remove trailing 'index.html'

---

source/docs/themes.md
source/ko/docs/themes.md
source/pt-br/docs/themes.md
source/ru/docs/themes.md
source/th/docs/themes.md
source/zh-cn/docs/themes.md
source/zh-tw/docs/themes.md

https://github.com/paularmstrong/swig deprecated since 2016, https://github.com/node-swig/swig-templates seems to be the reborn project

doc: update swig link

---

source/_posts/2019-12-09-hexo-4-1-released.md

Noticed this mistake when reviewing https://github.com/hexojs/site/pull/1242
"language-TERRITORY" should be used for existing multilingual/i8n support (theme typically uses this format). "language_TERRITORY" will break it.
"language-TERRITORY" is automatically transformed into "language_TERRITORY" in `open_graph()` helper.

news(hexo 4.1): 'language-TERRITORY' should be used for multilingual support

---

source/docs/tag-plugins.md
source/ko/docs/tag-plugins.md
source/pt-br/docs/tag-plugins.md
source/ru/docs/tag-plugins.md
source/th/docs/tag-plugins.md
source/zh-cn/docs/tag-plugins.md
source/zh-tw/docs/tag-plugins.md

The current example:
`{% img class-name /path/to/image 100 100 "title text 'alt text'" %}`
``` html
```
Notice the trailing space in the title attribute.
The correct usage is to quote both title and alt, then quote both of them:
`{% img class-name /path/to/image 100 100 '"title text" "alt text"' %}`
``` html
```
`"'title text' 'alt text'"` also works.
Closes https://github.com/hexojs/hexo/issues/1277

docs(img-tag): title text should be quoted

---

source/_posts/2020-03-08-hexo-renderer-markdown-it-4-1-0-hexo-util-1-9-0-released.md

- Languages:
---
Release news of [hexo-renderer-markdown-it 4.1.0](https://github.com/hexojs/hexo-renderer-markdown-it/releases/tag/4.1.0) and [hexo-util 1.9.0](https://github.com/hexojs/hexo-util/releases/tag/1.9.0)

chore(news): hexo-renderer-markdown-it 4.1.0 & hexo-util 1.9.0 released

---

source/_data/plugins.yml

This adds a `hexo-github-include` plugin to the list.
- Languages:

Update plugins.yml, add hexo-github-include

---

source/_posts/2020-04-30-hexo-util-2_hexo-fs-3.md

news: hexo-util 2.1.0 and hexo-fs 3.0.1

---

package.json

- Languages:
Closes #1410 as Hexo has dropped swig rendering support.

chore(deps): add hexo-renderer-swig

---

source/_data/sidebar.yml
source/api/injector.md
source/ko/api/injector.md
source/pt-br/api/injector.md
source/ru/api/injector.md
source/th/api/injector.md
source/zh-cn/api/injector.md
source/zh-tw/api/injector.md
themes/navy/languages/de.yml
themes/navy/languages/en.yml
themes/navy/languages/fr.yml
themes/navy/languages/ko.yml
themes/navy/languages/pt-br.yml
themes/navy/languages/ru.yml
themes/navy/languages/th.yml
themes/navy/languages/zh-cn.yml
themes/navy/languages/zh-tw.yml

- Languages:
https://github.com/hexojs/hexo/pull/4049
Closes #1447.

docs(injector): bring up

---

source/docs/configuration.md
source/ko/docs/configuration.md
source/pt-br/docs/configuration.md
source/ru/docs/configuration.md
source/th/docs/configuration.md
source/zh-cn/docs/configuration.md
source/zh-tw/docs/configuration.md

- Languages:
#1446 https://github.com/hexojs/hexo/issues/2471 https://github.com/hexojs/hexo/issues/3890

docs(configuration): add alternate theme config

---

source/api/injector.md
source/ko/api/injector.md
source/pt-br/api/injector.md
source/ru/api/injector.md
source/th/api/injector.md
source/zh-cn/api/injector.md
source/zh-tw/api/injector.md

- Languages:
Closes https://github.com/hexojs/hexo/issues/4446
Similar goal as https://github.com/hexojs/hexo-util#bindhexo

docs(injector): add more examples

---

source/_posts/2020-07-29-hexo-5-released.md

https://github.com/hexojs/hexo/issues/4450

news(hexo-5): mention 'use_date_for_updated' deprecation

---

source/api/injector.md
source/ko/api/injector.md
source/pt-br/api/injector.md
source/ru/api/injector.md
source/th/api/injector.md
source/zh-cn/api/injector.md
source/zh-tw/api/injector.md

https://hexo.io/api/helper#How-do-I-use-another-registered-helper-inside-my-custom-helper

docs(injector): helper must bind to hexo context

---

source/docs/index.md
source/ko/docs/index.md
source/pt-br/docs/index.md
source/ru/docs/index.md
source/th/docs/index.md
source/zh-cn/docs/index.md
source/zh-tw/docs/index.md

- also add warning about snap issue (https://github.com/nodesource/distributions/issues/843)
- Languages:

docs(index): sync Node.js guide across languages

---

themes/navy/source/css/_partial/page.styl

I often link to an api method and plugin using a backtick, but currently the links use `<code>` colour, so reader would only discern that it's a link when hover on it (which displays the underline).
````
[`foo`](/bar/baz)
````
A recent post is an example (https://hexo.io/news/2020/08/22/hexo-5-1_marked-3-1_math-4_util-2-4/), look for the following line.
````
* also available via [`codeblock`](/docs/tag-plugins#Code-Block) and [`include_code`](/docs/tag-plugins#Include-Code) tag plugins.
````
- Languages:

fix(css): set colour of `<code>` with link

---

source/api/renderer.md
source/api/rendering.md
source/ko/api/renderer.md
source/ko/api/rendering.md
source/pt-br/api/renderer.md
source/pt-br/api/rendering.md
source/ru/api/renderer.md
source/ru/api/rendering.md
source/th/api/renderer.md
source/th/api/rendering.md
source/zh-cn/api/renderer.md
source/zh-cn/api/rendering.md
source/zh-tw/api/renderer.md
source/zh-tw/api/rendering.md

Mainly to show example usage of `hexo.render.renderer.get()` method.
This also can be mentioned in [this section](https://hexo.io/docs/troubleshooting#Escape-Contents) https://github.com/hexojs/site/pull/1532.
- https://github.com/think-in-universe/hexo-stop-tag-plugins/blob/5494a7f7a0820f61673cb06258743c7caa181c0d/lib/overrider.js#L20-L23
- Languages:

docs(api/rendering): instruction to disable nunjucks

---

source/docs/troubleshooting.md
source/pt-br/docs/troubleshooting.md
source/th/docs/troubleshooting.md
source/zh-cn/docs/troubleshooting.md
source/zh-tw/docs/troubleshooting.md

- Languages:
`plugins` option removed in https://github.com/hexojs/hexo/pull/4475
See also https://github.com/hexojs/site/pull/459

Remove docs about plugins option

---

source/docs/front-matter.md

Easy navigation and easy reading for others
- Languages:

Fix broken url in docs

---

source/_data/themes.yml

For some reason, https://mrwillcom.now.sh/ becomes the official website of theme Cupertino.
Already checked the check list.
Thanks!

Update preview link for theme Cupertino

---

source/_posts/2021-05-05-hexo-util-2-5-0-released.md

Add release news of [hexo-util 2.5.0](https://github.com/hexojs/hexo-util/releases/tag/2.5.0)
> https://github.com/hexojs/hexo-util/pull/249
- Languages:

chroe(news): release news of hexo-util 2.5.0

---

source/ko/docs/tag-plugins.md

- Languages:
The YouTube embed plugin expects a type as the second parameter:
https://github.com/hexojs/hexo/blob/fc2979a43e2c04de045625de752d7674daa4db15/lib/plugins/tag/youtube.js#L12
If you don't provide a type but a boolean, then the plugin tries to render a playlist and fails with a plain video embed. That's why `{% youtube lJIrF4YjHfQ false %}` cannot be used as a shortcut to create privacy-enhanced embeds. It must be `{% youtube lJIrF4YjHfQ 'video' false %}`.

docs: fix privacy-enhanced YouTube video embed

---

netlify.toml
source/docs/gitlab-pages.md

As said on the doc page itself: In .gitlab-ci.yml file, the node version needs to be updated to Nodejs version > 12.0.0, otherwise the pipeline will fail with error TypeError: line.matchAll is not a function

gitlab-ci node version upgrade

---

source/docs/helpers.md
source/ko/docs/helpers.md
source/pt-br/docs/helpers.md
source/ru/docs/helpers.md
source/th/docs/helpers.md
source/zh-cn/docs/helpers.md
source/zh-tw/docs/helpers.md

- Languages:
Add some description: `author` `date` `updated` `language` 
https://github.com/hexojs/hexo/issues/4814 If the theme has a custom author config, you need to modify the Open Graph options as well
example:
```js
open_graph({author: config.author.nick})
```

docs(open_graph): add some description

---

source/_posts/2021-11-26-hexo-renderer-ejs-2-0-0-and-hexo-generator-sitemap-2-2-0-released.md

Release news of [hexo-generator-sitemap 2.2.0](https://github.com/hexojs/hexo-generator-sitemap/releases/tag/2.2.0) and [hexo-renderer-ejs 2.0.0](https://github.com/hexojs/hexo-renderer-ejs/releases/tag/2.0.0)
- Languages:

news: hexo-renderer-ejs 2.0.0, hexo-generator-sitemap 2.2.0 released

---

source/docs/github-pages.md

Node.js v12 ships with npm v6, which uses version 1 of `package-lock.json`. Node.js v15+ ships with npm v7+, which currently uses version 2 of this file. If user has a version 2 `package-lock.json` in their repo, npm v6 may have trouble reading it, so the `Pages` workflow may fail. This should be avoided by guiding the user to use the same version of Node.js that they work with locally.
I left a [comment on the page](http://disq.us/p/2lbsr4c) with this detail, and also made a [blog post](https://murchu27.github.io/2021/12/13/Deploying-your-Hexo-blog-on-GitHub-Pages/).
- Languages:

Updating Node.js version in `pages.yml` example

---

source/api/posts.md
source/api/tag.md
source/docs/themes.md
source/docs/troubleshooting.md
source/ko/api/posts.md
source/ko/api/tag.md
source/ko/docs/themes.md
source/ko/docs/troubleshooting.md
source/pt-br/api/posts.md
source/pt-br/api/tag.md
source/pt-br/docs/themes.md
source/pt-br/docs/troubleshooting.md
source/ru/api/posts.md
source/ru/api/tag.md
source/ru/docs/themes.md
source/ru/docs/troubleshooting.md
source/th/api/posts.md
source/th/api/tag.md
source/th/docs/themes.md
source/th/docs/troubleshooting.md
source/zh-cn/api/posts.md
source/zh-cn/api/tag.md
source/zh-cn/docs/themes.md
source/zh-cn/docs/troubleshooting.md
source/zh-tw/api/posts.md
source/zh-tw/api/tag.md
source/zh-tw/docs/themes.md
source/zh-tw/docs/troubleshooting.md

Hexo has already been changed default renderer.
Change the description of the default renderer from Swig to Nunjucks.
- Languages:

chore(docs): change the description of the default renderer from Swig to Nunjucks

---

source/docs/syntax-highlight.md
source/ko/docs/syntax-highlight.md
source/pt-br/docs/syntax-highlight.md
source/ru/docs/syntax-highlight.md
source/th/docs/syntax-highlight.md
source/zh-cn/docs/syntax-highlight.md
source/zh-tw/docs/syntax-highlight.md

refs: https://github.com/hexojs/hexo/pull/3865
- Languages:

docs: add exclude_languages option

---

.github/workflows/tester.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

source/_data/plugins.yml

Suppose you use the http forced cache, when your static resources change, the user can not get the latest resources, the user can clean the cache to get the latest resources, but this will clean all the cache, the plug-in will generate a hash of the file content to control the version, when the content changes, the url address will change, without cleaning all the cache, you can get the latest resources

Add plugin: hexo-hash

---

source/docs/helpers.md
source/zh-cn/docs/helpers.md

feat(helper/tagcloud): show_count option (hexojs/hexo#5047, hexojs/hexo#5048)

---

source/docs/helpers.md
source/zh-cn/docs/helpers.md

feat(paginator): custom class name (hexojs/hexo#5001)

---

source/docs/helpers.md
source/zh-cn/docs/helpers.md

The current `hexo.io` does not support versioning. So, I marked `(+6.3.0)` to new features for `v6.3.0`. Because user can't understand which features are adopted in `6.3.0`. Also I [have already marked `(+6.1.0)` when release `v6.1.0`](https://github.com/yoshinorin/site/commit/c310b62358a36f8f42e2399cc83e97f14f307535) same with this PR.
* refs: https://github.com/hexojs/site/pull/1902
* refs: https://github.com/hexojs/site/pull/1886
* refs: https://github.com/hexojs/site/pull/1885
* refs: https://github.com/hexojs/site/pull/1873
- Languages:

docs: add `(+6.3.0)` mark for an adopted feature in v6.3.0

---

source/docs/github-pages.md
source/zh-cn/docs/github-pages.md
source/zh-tw/docs/github-pages.md

There are some issues with this document.
- Github do not support the name of token starting with `GITHUB_`.
Check the issue here -> https://github.com/github/docs/issues/12094
- The name of `token` in the `pages.yml` is ambiguous. User may check the usage of actions.
- Languages:
> **Note**
>
> **Warning**
>

[update] new hints in the example of github-pages.md

---

source/docs/troubleshooting.md

- some errors are not gracefully handled by [`formatNunjucksError`](https://github.com/hexojs/hexo/blob/bbf09ac00f67a7f943d6be2e473e1242da9383e6/lib/extend/tag.js#L162), hence affected lines are not shown.
- this PR adds some examples of common mistake in using tag plugin.
- related to https://github.com/hexojs/hexo/pull/5031
- Languages:

docs(troubleshooting): add examples of template render error

---

source/docs/plugins.md
source/docs/themes.md

docs: update themes, plugins

---

source/docs/configuration.md

docs(configuration): fix wrong link

---

themes/navy/layout/partial/plugin.njk
themes/navy/layout/partial/theme.njk
themes/navy/layout/plugins.njk
themes/navy/source/css/_partial/plugins.styl

Current theme page has some issues.
1. If we click theme image thumb, we will be transfer to external site.
* I think this is not not intuitive behavior.
* Not good for security reasons.
2. User can not understand which link is external or not.
This PR is temporary solution for these issues.
refs: https://github.com/orgs/hexojs/discussions/5267#discussioncomment-6716225
---
Thank you :)

chore(theme/plugin): improve external links behavior and visibility

---

package.json

from lint-staged v10, `git add` is unnecessary

chore(lint-staged): remove `git add`

---

source/zh-cn/docs/plugins.md
source/zh-cn/docs/themes.md

- Languages:
update docs related to https://github.com/hexojs/site/pull/2042

docs(zh-cn): update themes, plugins

---

source/docs/front-matter.md
source/ru/docs/front-matter.md
source/zh-cn/docs/front-matter.md
source/zh-tw/docs/front-matter.md

See https://github.com/hexojs/hexo/issues/5122

docs(front-matter): describe variable `published`

---

source/zh-cn/docs/syntax-highlight.md

- Languages:
> **Note**
>
> **Warning**
>

docs(zh-cn): fix typo

---

source/_data/plugins/hexo-pro.yml

Add a plugin called hexo pro to the plugin list, which enables hexo to support backend editing and publishing of blogs in server mode

plugin: add hexo-pro

---

source/docs/github-pages.md

- Languages:
> **Note**
>
> **Warning**
>
There is no need to have a `gh-pages` branch anymore.
See also:
- https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta/
- https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow
- https://github.com/marketplace/actions/deploy-github-pages-site

docs: use GitHub Actions to deploy to GitHub Pages directly

---

source/docs/github-pages.md
source/zh-cn/docs/github-pages.md

related PR #1909
submodule is acceptable
- Languages:

docs(deployment): update github-pages for git submodule

---

source/zh-cn/docs/github-pages.md

- Languages:
> **Note**
>
> **Warning**
>
See also:
https://github.com/hexojs/site/pull/2078

docs(zh-cn): use GitHub Actions to deploy to GitHub Pages directly

---

source/docs/configuration.md
source/docs/contributing.md
source/docs/front-matter.md
source/docs/github-pages.md
source/docs/helpers.md
source/docs/one-command-deployment.md
source/docs/syntax-highlight.md
source/docs/tag-plugins.md
source/docs/themes.md
source/docs/troubleshooting.md
source/docs/writing.md

- Languages:
> **Note**
>
> **Warning**
>
Minor improvements in files under docs/ directory

docs: fix gramatical and typographical errors

---

source/docs/commands.md
source/docs/syntax-highlight.md
source/ru/docs/commands.md
source/ru/docs/gitlab-pages.md
source/ru/docs/syntax-highlight.md
source/zh-cn/docs/commands.md
source/zh-cn/docs/configuration.md
source/zh-cn/docs/gitlab-pages.md
source/zh-cn/docs/index.md
source/zh-cn/docs/syntax-highlight.md
source/zh-tw/docs/commands.md
source/zh-tw/docs/gitlab-pages.md
source/zh-tw/docs/syntax-highlight.md

- Languages:
> **Note**
>
> **Warning**
>

docs: update link

---

source/docs/helpers.md
source/ja/docs/helpers.md
source/ko/docs/helpers.md
source/pt-br/docs/helpers.md
source/ru/docs/helpers.md
source/th/docs/helpers.md
source/zh-cn/docs/helpers.md
source/zh-tw/docs/helpers.md

- Languages:
The value `blog` specified as the default value for `og:type` is incorrect. As per the following implementation:
https://github.com/hexojs/hexo/blob/v7.1.1/lib/plugins/helper/open_graph.ts#L82
The default value is `article` or `website` depending on whether it is a post page or not.
The default value of `og:locale` is chosen from several settings, as implemented below:
> `page.lang || page.language || config.language`
Although this was written in the documentation, the `|` in this code was treated as a table separator, resulting in the display being cut off in the middle. I fixed it by escaping `|`.
Before fix:
After fix:

docs(helpers/open_graph): Fix incorrect default value and unintended rendering

---

scripts/helpers.js
source/about/index.md
themes/navy/layout/about.njk
themes/navy/layout/partial/head.njk

There is a problem with the `canonical` and `alternative` URL annotations in the `<head>` tag of the page where the translation exists.
This is probably why when we search for "hexo" on Google, we get strange results in some languages.
This pull request provides corrections to errors and improvements in `<head>`, with the aim of displaying search results as naturally as possible.
For example, https://hexo.io/zh-tw/api/ outputs the following (excerpt):
```html
<html lang="zh-tw">
<head prefix="og: http://ogp.me/ns#">
<link rel="canonical" href="https://hexo.io/zh-tw/api/index.html"> 
<link rel="alternative" hreflang="en" href="https://hexo.io/zh-tw/api/">
<link rel="alternative" hreflang="zh-tw" href="https://hexo.io/zh-tw/zh-tw/api/">
<link rel="alternative" hreflang="zh-cn" …
```

fix: incorrect `canonical` and `alternative` URL annotations

---

.github/workflows/cleaner.js
.github/workflows/cleaner.yml

I have improved a script I wrote earlier that can automatically check whether the links for themes and plugins have been updated or become invalid, and it periodically opens a pull request to update them.
See https://github.com/hexojs/site/pull/1458#issuecomment-650570884

chore: use GitHub actions to sanitize themes & plugins list

---

source/_posts/2024-04-17-hexo-7-2-0-released.md

refs: https://github.com/hexojs/hexo/pull/5453
- Languages:

chore: release news v7.2.0

---

.github/workflows/crowdin-pr.yml
.github/workflows/crowdin-upload-tran.yml
.github/workflows/crowdin-upload.yml
README.md
crowdin.yml

#2119
add ci for integrating with crowdin
- Languages:

ci: add workflows of integrate with crowdin

---

source/docs/helpers.md

docs(helpers/list_tags): fix typo

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
source/docs/contributing.md

update contributing guide of translations
resolve https://github.com/hexojs/site/issues/2119
- Languages:

update contributing guide of translations

---

source/docs/contributing.md

fix(en/contributing): fix typo

---

source/_data/plugins/hexo-deployer-pulumi.yml

This deployment plugin uses Pulumi (an infrastructure-as-code tool) to deploy a Hexo site to Amazon S3. This allows a user to track and manage deployments via Pulumi Cloud along with their other infrastructure. It's also easily forkable to modify the Pulumi code to integrate your site build/publish into your other IaC code.

Add hexo-deployer-pulumi plugin

---

source/_data/plugins/hexo-deployer-s3-qiniu.yml

Add plugin hexo-deployer-qiniu-s3 to sync static pages to [Qiniu](https://www.qiniu.com/)  s3 storage.

Add plugin hexo-deployer-qiniu-s3

---

source/docs/troubleshooting.md

- Languages:
The current  troubleshooting doc is truncated.

docs: fix truncated troubleshooting doc

---

source/_data/plugins/hexo-htmlnano-mini.yml

add plugin hexo-htmlnano-mini

---

source/_data/plugins/hexo-bluesky-feed.yml

I’m excited to announce `hexo-bluesky-feed` — an open source Hexo plugin that can publish your latest blog post to [Bluesky](https://bsky.app/) whenever you generate your Hexo site with the --bluesky flag.
With `hexo-bluesky-feed`, if you run `hexo generate --bluesky`, the plugin will:
- Obtain a fresh access token: It uses your Bluesky handle and an app password (set via environment variables) to securely fetch a new access token and your DID.
- Select your latest post: The plugin sorts your posts by their publication date, ensuring the most recent post is used.
- Construct a dynamic update message: It builds a message using a customizable template and attaches a clickable link to your post.
- Post directly to Bluesky: The update is sent using Bluesky’s API so that your social feed stays …

Add hexo-bluesky-feed plugin

---

themes/navy/source/css/_partial/page.styl

this var never be defined in `.styl` and could no be complied by stylus. It may be caused by typo.
https://hexo.io/docs/tag-plugins

fix(navy): a inexistent stylus variable
