hexojs/site

source/_data/plugins.yml

This adds two renderer plugins to the directory:
- hexo-renderer-markdown-it
- hexo-renderer-bourbon

Add hexo-renderer-markdown-it and hexo-renderer-bourbon

---

source/zh-cn/docs/commands.md
source/zh-cn/docs/helpers.md
source/zh-cn/docs/migration.md
source/zh-cn/docs/plugins.md
source/zh-cn/docs/themes.md

Update zh-cn doc

---

source/_data/plugins.yml

Add Spotify tag [widget](https://github.com/ivanovyordan/hexo-tag-spotify) to the plugins list.

Add spotify plugin to the plugins list

---

source/_data/plugins.yml

Fix a wrong link. Sorry for the mistake.

Fix the wrong link of hexo-tag-bootstrap.

---

source/docs/commands.md
source/docs/configuration.md
source/docs/index.md
source/docs/migration.md
source/docs/setup.md
source/docs/themes.md
source/docs/writing.md

Simplify and correct the English grammar for some of the Hexo documentation

Improve documentation grammar

---

source/_data/plugins.yml

This tag plugin  can work with plantuml to draw uml

add hexo tag plugin plantuml

---

source/docs/deployment.md

deployer should be deploy

---

source/docs/asset-folders.md
source/docs/tag-plugins.md
source/zh-cn/docs/asset-folders.md
source/zh-cn/docs/contributing.md
source/zh-cn/docs/tag-plugins.md
source/zh-tw/docs/asset-folders.md
source/zh-tw/docs/tag-plugins.md

asset img fix

---

source/_data/plugins.yml

this plugin can sync static file to Qiniu CDN Automatic

add Qiniu CDN sync plugin

---

source/_data/plugins.yml

Added a new plugin into the plugin's list.

Added googlecharts plugin

---

source/docs/index.md
source/zh-cn/docs/index.md
source/zh-tw/docs/index.md

msysgit在google code上的库已经被转移了，所以更新了一下链接。

fix the git download link for win

---

source/docs/index.md
source/zh-cn/docs/index.md
source/zh-tw/docs/index.md

fix the link of osx-git-install

---

source/_data/plugins.yml

https://github.com/willin/hexo-wordcount
http://blog.willin.wang

Add wordcount plugin

---

source/_data/plugins.yml

This plugin was inspired by the [Ruby template](http://zh.moegirl.org/Template:Ruby) of 萌娘百科.
http://blog.jamespan.me/2015/06/21/hexo-ruby-character/

add plugin hexo-ruby-character

---

source/_data/plugins.yml

yet another hexo-migrator-blogger plugin

---

source/_data/plugins.yml

Added the hexo-tag-flickr plugin to plugins list

Added plugin hexo-tag-flickr

---

source/_data/plugins.yml

Remove unused styles from CSS with [uncss](https://github.com/giakki/uncss).

Added hexo-uncss.

---

source/_data/plugins.yml

Minify image assets using [imagemin](https://github.com/imagemin/imagemin).

Added hexo-imagemin.

---

source/_data/sidebar.yml
source/docs/internationalization.md
source/zh-cn/docs/internationalization.md
source/zh-tw/docs/internationalization.md
themes/navy/languages/en.yml
themes/navy/languages/zh-cn.yml
themes/navy/languages/zh-tw.yml
themes/navy/source/css/_variables.styl

I replace everywhere localization by internationalization (i18n).
i18n : internationalization
l10n : localization

Fix mistake : i18n is internationalization

---

source/_data/themes.yml

Thanks for accept my request just before.
Fixed a small mistake in themes.yml. (wrong theme repository, Sorry!)

Fix Theme : zzoman2015 Repository

---

source/_data/plugins.yml

Add news plugins to list:
hexo-tag-vine ~>  Allows to you embed vine videos in your posts/pages
hexo-tag-xvideos ~> Allows to you embed xvideos player in your posts/pages

add new plugins: hexo-tag-vine and hexo-tag-xvideos

---

source/_data/plugins.yml

hexo-hey is an admin plugin for hexo

Add hexo-hey

---

source/_data/plugins.yml

Adds an entry for [hexo-admin](https://github.com/jaredly/hexo-admin/)

add Hexo Admin to plugins list

---

source/_data/plugins.yml

bilibili.com embedded videos for hero.

Add hexo-tag-bilibili

---

source/_data/plugins.yml

My fault. I forgot that I have already submitted this plugin and mistakenly did it again. Now remove it.

Remove duplicate plugin.

---

source/_data/plugins.yml

Follow the name rules. Excuse me.

changed repository name

---

source/_data/plugins.yml

Hexo renderer plugin for emacs org-mode:https://github.com/CodeFalling/hexo-renderer-org

Add plugin:hexo-renderer-org

---

source/api/box.md
source/api/console.md
source/api/deployer.md
source/api/events.md
source/api/filter.md
source/api/generator.md
source/api/helper.md
source/api/index.md
source/api/migrator.md
source/api/posts.md
source/api/processor.md
source/api/renderer.md
source/api/rendering.md
source/api/router.md
source/api/tag.md
source/api/themes.md
source/docs/helpers.md

Went through the API docs as well

Spelling & grammar

---

source/docs/setup.md

fixed https://github.com/hexojs/hexo-cli/issues/4

remove scripts in hexo init directory

---

source/docs/troubleshooting.md

Added solution to the error ENOSPC on Linux when running `hexo server`

updated troubleshooting.md

---

source/_data/plugins.yml

hexo-pdf: A plugin to display pdf in hexo posts/pages

---

source/_data/plugins.yml

HEXO has upgraded to 3.XX.
Since most of the optimize plugins for HEXO have been deprecated or loss maintenance([hexo-optimize](https://www.npmjs.com/package/hexo-optimize),[hexo-console-optimize](https://www.npmjs.com/package/hexo-console-optimize),[hexo-generator-optimize](https://www.npmjs.com/package/hexo-generator-optimize)), so I decide to implement this plugin.
Integrate all official minify plugins and a imagemin plugin. All in one.
I will try to maintain this plugin for a long time.

Apply for publishing pugin

---

source/_data/plugins.yml

Add hexo-autonofollow to plugins list.

Add hexo-autonofollow to plugins list.

---

source/_data/plugins.yml

The old repo still exists fwiw

renamed my hexo-easy-edit plugin to hexo-cli-extras as it does more stuff now

---

source/_data/plugins.yml

Adds the hexo-generator-postmap plugin.

Add hexo-generator-postmap

---

source/_data/plugins.yml

A hexo tag for inserting youku video in your blog.

adding hexo-tag-youku

---

source/_data/plugins.yml

A hexo tag for inserting echarts chart in your blog.

adding hexo-tag-echarts

---

source/_data/plugins.yml

Add hexo-deployer-ansible

---

source/_data/plugins.yml

Hi, I made a simple hexo plugin for canonical link.

Add hexo-auto-canonical plugin

---

source/_data/themes.yml

I am so sorry，the website is 'http://jser.it'.

modify website for "Simpe" theme

---

source/_data/plugins.yml

Tag plugin for generating admonition html structure similar to [Python markdown admonition](https://pythonhosted.org/Markdown/extensions/admonition.html).
Sample styling see this [codepen](http://codepen.io/haishanh/pen/zqqbmq/?editors=1100).

Add tag plugin admonition

---

source/_data/plugins.yml

change the default tag cloud to a tag cloud ball

add hexo-tag-cloud plugin

---

source/_data/plugins.yml

Hi,
I've created a plugin that applies critical (CSS) to the HTML files.  This pull request adds hexo-critical-css to the list of plugins in the hexo site.
Thanks,

Add hexo-critical-css plugin

---

source/_data/themes.yml

add Theme Huxblog

---

source/_data/plugins.yml

I created a new plugin that uses deployer-s3 and adds cloudfront invalidation to it.

Add new hexo-deployer-s3-cloudfront plugin

---

source/_data/plugins.yml

plugins:
- hexo-generator-recent
- hexo-index-anything
- hexo-thumbnails
- hexo-imgur

added four plugins

---

source/_data/plugins.yml

add plugin hexo-tag-dplayer

---

source/_data/plugins.yml

add 2 useful plugin

---

source/_data/themes.yml

just change my themes link , thanks :)

change Anisina theme link

---

source/_data/themes.yml

I change my themes link , thanks again ：）

change Anisina theme preview links

---

source/_data/plugins.yml

add a new plugin named hexo-encrypt

add plugin hexo-encrypt

---

source/_data/plugins.yml

I created a new tag plugin to integrate leaflet based OSM maps and added the description to the plugin.yml file.

added description for new plugin hexo-tag-leaflet

---

source/_data/plugins.yml

Allow post to embed asciinema using {% asciinema [video_id] %}

Add asciinema plugin

---

source/_data/plugins.yml

add a plugin

---

source/_data/plugins.yml

hexo-tag-video_cn is a hexo plugin for inserting youku or tencent video in your site

Add a plugin for hexo

---

source/_data/themes.yml

A medium-like image lazyload plugin

add hexo-medium-image plugin

---

source/_data/plugins.yml
source/_data/themes.yml

Sorry for adding plugin to the theme category yesterday. Now, It's fixed.
Thank you so much!

update hexo-medium-image plugin

---

source/_data/plugins.yml

A plugin to index posts of your Hexo blog on Algolia

Add hexo-algoliasearch plugin

---

source/_data/plugins.yml

https://github.com/zhenyong/hexo-filter-file-link#readme

add hexo-filter-file-link plugin description

---

source/_data/plugins.yml

Added hexo-related-popular-posts reference. Please marge it.

Added hexo-related-popular-posts reference.

---

source/ru/docs/index.md
source/zh-cn/docs/index.md
source/zh-tw/docs/index.md

Change Node.js install command from `nvm install 4` to `nvm install stable`.

Fix typo: Node.js install command

---

source/_data/plugins.yml

Postrender your posts with hanzi (漢字標準格式).

Add hexo-hanzi plugin

---

source/_data/plugins.yml

borrow taxonomy function from hugo

add taxonomy plugin

---

source/_data/plugins.yml

This is update that added plugin (hexo-tag-instagram plugin). Please marge it.

This is update that added plugin (hexo-tag-instagram plugin)

---

source/_data/plugins.yml

Added hexo-tag-twentytwenty. Please marge it.

added hexo-tag-twentytwenty

---

source/_data/plugins.yml

A new plugin to integrate azure search service.

Add hexo-azuresearch plugin

---

source/_data/plugins.yml

A plugin to easily create a demo area (html, css, javascript) in the post content.

added hexo-tag-demo

---

source/_data/plugins.yml

Hello,
I have created plugin to display reading time for the article. So with this pull request I'd like to add the plugin to site.

Add hexo-reading-time plugin

---

source/_data/plugins.yml

Adds my sliding spoiler plugin which does this:

Add hexo-sliding-spoiler

---

source/_data/plugins.yml

Add Hexo Plugin to add Apester interactive contents using tags

Add plugin hexo-tag-apester

---

source/docs/themes.md

Added pug renderer

---

source/_data/plugins.yml

adding pug renderer

---

source/_data/plugins.yml

Add hexo-algolia

---

source/_data/plugins.yml

Register hexo-slack-notify into plugins.yml

Register hexo-slack-notify into plugins.yml

---

source/_data/plugins.yml

Add helper to get available languages on a page

---

source/_data/plugins.yml

There was a syntax error in tags from hexo-baidu-url-submit i copied down in my previous pull request

Fix sytax error for tags

---

source/docs/commands.md
source/docs/configuration.md

Added information from https://github.com/hexojs/hexo/pull/2211 to site docs.

Multiple config file info added to Docs

---

source/_data/plugins.yml

original plugin is no longer maintained.

Add plugin hexo-tag-echarts3.

---

source/_data/plugins.yml

Added Hexagon, a Hexo package manager, to the plugin list

Added Hexagon to plugin list

---

source/_data/plugins.yml

Updated hexo-related-popular-posts description. Please marge it.

Updated hexo-related-popular-posts description.

---

source/_data/plugins.yml

Converts local URLs to CDN ones when `hexo generator`.
https://github.com/zqjimlove/hexo-cdnify

add hexo-cdnify

---

source/_data/plugins.yml

Add a new plugin, using d3-cloud to generate tagcloud for Hexo. 
Demo : http://lucyhao.com/tags

add a new plugin

---

source/ru/index.jade

Hi!
According to https://goo.gl/th3DUu correct translation for word framework is "фреймворк"

Fix translation of framework

---

package.json
source/_data/plugins.yml

The plugin is used to generate itunes-friendly podcast rss file.
Added support for chapter.

Added plugin `hexo-generator-podcast`.

---

source/_data/plugins.yml

Github emojis with unicode fallback. :tada:

Added plugin `hexo-filter-github-emojis` :tada:

---

source/_data/plugins.yml

plugin repo: https://github.com/aspirewit/hexo-tag-easy-charts

Add plugin hexo-tag-easy-charts

---

source/zh-cn/docs/commands.md
source/zh-cn/docs/configuration.md
source/zh-cn/docs/deployment.md
source/zh-cn/docs/front-matter.md
source/zh-cn/docs/generating.md
source/zh-cn/docs/helpers.md
source/zh-cn/docs/index.md
source/zh-cn/docs/migration.md
source/zh-cn/docs/server.md
source/zh-cn/docs/setup.md
source/zh-cn/docs/troubleshooting.md

这些内容是我刚接触Hexo时阅读文档所不太了解的地方，因此想把这些补充进官方文档中。

补充了原文档中描述不太清晰的一部分内容

---

source/_data/plugins.yml

add plugin hexo-helper-live2d

---

source/_data/plugins.yml

Added hexo-tag-twitter plugin.

---

source/_data/plugins.yml

Added Aliyun deployer plugin.

---

source/_data/plugins.yml

the plugin is based on the lib normalizr, which is nearly-perfectly solve the problem of the multi-nested object when creating SPA and using some state manege lib such as Redux, Vuex and so on.

Add the plugin hexo-generator-to-json

---

source/_data/themes.yml

SSL Error + Not really configured site

Replace dead preview - carbon

---

source/_data/themes.yml

https://github.com/ghaseminya/hexo-theme-icarus_rtl_jalaali

add new theme

---

source/_data/plugins.yml

Sass renderer plugin for Hexo with Bourbon/Neat support.

Added plugin hexo-renderer-bourbon-sass-neat to list

---

source/docs/deployment.md

Added info on using https://github.com/lucascaro/hexo-deployer-sftp for sftp deploys.

Add info on deploying via SFTP

---

source/_data/plugins.yml

Add [hexo-renderer-asciidoc](https://github.com/hcoona/hexo-renderer-asciidoc) plugin

Add hexo-renderer-asciidoc plugin

---

source/_data/plugins.yml

add [hexo-translate-title](https://github.com/cometlj/hexo-translate-title) plugin

add hexo-translate-title plugin

---

source/_data/plugins.yml

add plugin ``Top and Index generator plugin for Hexo``.

add plugin hexo-generator-topindex

---

source/_data/plugins.yml

Index generator plus for Hexo, including new order attributes like top and updateDate.

new index-generator plugin for Hexo

---

source/docs/troubleshooting.md

Add render error solution in troubleshooting.md

Add render error in troubleshooting.md

---

source/_data/plugins.yml

Add [hexo-filter-plantuml](https://github.com/wafer-li/hexo-filter-plantuml) plugin

Add hexo-filter-plantuml

---

source/docs/data-files.md
source/ko/docs/data-files.md
source/ru/docs/data-files.md
source/zh-cn/docs/data-files.md
source/zh-tw/docs/data-files.md

UPDATE data-files.md for hexo-3.3.1

UPDATE data-files.md for hexo-3.3.1

---

source/zh-cn/docs/contributing.md

修正Google JavaScript Style Guide链接

---

source/_data/themes.yml

change demo link of theme what named another

---

source/_data/plugins.yml

Add slide layout in hexo site using reveal.js

add plugin hexo-slides-reveal

---

source/docs/index.md
themes/navy/languages/de.yml

Fixed nvm install script changes and added colons

---

source/docs/helpers.md

Document `max_depth` option for toc()

---

package.json
source/_data/plugins.yml

add hexo-douban plugin

---

source/_data/plugins.yml

Add hexo-excerpt-block and hexo-description plugins

---

source/_data/plugins.yml

Add a plugin to support JS, CSS, HTML, image minification/optimisation. 
Add support for revisioning of files.
PS: There are some already available plugins for minification but thier dependencies are not updated and they do not support revisioning so I had to write this one.
Closes #505

Plugin: hexo-asset-pipeline

---

source/_data/themes.yml

modify theme vexo's preview_link

---

source/docs/variables.md

I believe it's mostly correct but some are missing as I wan't quite able to figure them out. I hope someone more familiar with the project could finish it :)

Add documentation of variable types

---

source/_data/plugins.yml

Adding hexo-codepen and hexo-caniuse plugin.

---

source/zh-cn/docs/front-matter.md

This PR is intended to fix the improper display of YAML clip in [this page](https://hexo.io/zh-cn/docs/front-matter.html ). [Here](https://patch-3--landlord-dog-27842.netlify.com/zh-cn/docs/front-matter ) shows the generated page of the change.

Fix improper YAML display

---

source/_data/plugins.yml

This add renderer `hexo-renderer-markdown-it-plus` to the directory.

adding hexo-renderer-markdown-it-plus plugin

---

source/_data/themes.yml

Update hexo-theme-jane info

---

source/_data/plugins.yml

Adding hexo-cloudinary plugin.

---

source/_data/plugins.yml

I recently created this plugin and it will make any hexo support lazyload image in seconds. I also test it in some top hexo themes, all them works good.

Add hexo-lazyload-image plugin

---

source/_data/plugins.yml

add new plugin: hexo-tag-cplayer

---

source/_data/plugins.yml

Support mustache

---

source/_data/plugins.yml

Add my plugin: hexo-minecraft-templates

Adding hexo-minecraft-templates

---

source/_data/plugins.yml

Sorry for that.. I'm so foolish to code with the wrong format

Fix hexo-minecraft-templates link

---

source/docs/front-matter.md

Update to support changes in Hexo issue 848 (PR 2734)

Describe how to assign multiple categories

---

source/_data/plugins.yml

add a performance hexo-lazyload plugin
use Intersectionobserver API with polyfill

add a performance hexo-lazyload plugin

---

package.json
source/docs/asset-folders.md
source/docs/data-files.md
source/docs/front-matter.md
source/docs/generating.md
source/docs/helpers.md
source/docs/index.md
source/docs/setup.md
source/docs/tag-plugins.md
source/docs/templates.md
source/docs/themes.md
source/docs/variables.md
source/docs/writing.md

Hey, I love what you guys are doing with Hexo! I added some tutorial videos that I made to relevant pages on the docs. Hopefully these can help the users on the docs to gain a fuller understanding of the core concepts!!
Here's a link to the full video playlist: 
https://www.youtube.com/watch?v=Kt7u5kr_P5o&list=PLLAZ4kZ9dFpOMJR6D25ishrSedvsguVSm

Added several video tutorials teaching concepts on some of the doc pages

---

source/_data/plugins.yml

Add plugin hexo-filter-inline-images

---

source/_data/plugins.yml

Add hexo-generator-mip plugin

---

source/_data/plugins.yml

Add metadata entry for hexo-global-license plugin to the plugins.yml file.

Add hexo-global-license to the plugin list

---

source/_data/plugins.yml

Hexo plugin to add on hexo site.
hexo-auto-excerpt - Auto excerpt plugin for hexo. No need to manually add  tag.

hexo plugin auto excerpt

---

source/_data/themes.yml

update preview for theme Archer.
The [new preview link](http://firework.studio/archer-demo/)

update preview for theme Archer

---

source/_data/plugins.yml

a plugin for img manipulation via imagemagick

added hexo-img-optimization to plugin yaml

---

source/_data/themes.yml

theme(Inisde): fix preview address

---

themes/navy/source/js/plugins.js

Fix plugins search

---

source/_data/plugins.yml

I used many CMS throughout the years and with many of them it was common to have custom fields, which is a functionality that allows the coder to be able to include just snippets of text or an image path into a template. This plugin tries to add this functionality directly from the Markdown source files.

Update plugins.yml with my plugin 'hexo-custom-fields'

---

source/_data/themes.yml

add themes sw-blog

---

source/_data/plugins.yml

include hexo-recommended-posts plugin

---

source/pt-br/api/generator.md

Update in Generator page.
Original [commit](https://github.com/hexojs/site/commit/2fc89f7731683304ceb2dc124aa32e36f7edf2e5)

Page 'Generator' from 'API' updated

---

source/_data/themes.yml

Fix the issue of broken themes.yml. 
The bug was introduced in PR #625.
Closes #626

bug(theme): Fix broken theme.yml

---

source/_data/plugins.yml

add hexo-blogroll plugin

---

source/docs/deployment.md

Typo, duplicated property

---

source/_data/themes.yml

Update the theme preview error link and add tag

Update the theme preview link

---

source/_data/themes.yml

change the preview site of my theme Archer  😀

change preview site of theme Archer

---

source/_data/themes.yml

Update theme-nlvi info

---

source/_data/plugins.yml

It's a hexo plugin that optimize the pages loading speed, by the configurable lazyload, inline css, and bundle files into the one.

add hexo-filter-optimize plugin.

---

source/_data/plugins.yml

Add hexo-renderer-markdown

---

source/_data/plugins.yml

l push a plugin ,A hexo plugin, using Baidu JS automatic link push method, submit links to Baidu.
thanks.

add hexo-baidu-url-push

---

source/_data/themes.yml

更新Ada主题的预览地址

---

source/api/helper.md

Add FAQ: where to place custom helper.

docs: helper.md | Add FAQ: where to place custom helper.

---

source/docs/helpers.md

docs | add hint about how to create custom helper.

---

source/_data/plugins.yml

A small plugin to render inline SVG icons directly from Font Awesome library

Add hexo-fontawesome plugin

---

source/pt-br/api/helper.md
source/pt-br/docs/helpers.md

References:
* https://github.com/hexojs/site/commit/a5acd49defdae405e1902c1354de95b6c19a113e#diff-caf0a426223c1cc89f44edcdab0171f8
* https://github.com/hexojs/site/commit/8c212b0325d02c25f661f83e66f6486727102a1c#diff-f00ba5800b1104273a9c083b4ba2c991

Updated Portuguese documentation

---

source/docs/templates.md

Fix typo in variable

---

source/docs/configuration.md

Polish wording.
Originally submitted by @BitYog as https://github.com/hexojs/hexojs.github.io/pull/5

Update documentation for configuration

---

source/_data/plugins.yml

Added hexo-deployer-netlify and hexo-deployer-getforge plugins.

added netlify and getforge deployer plugins

---

source/_data/plugins.yml

add hexo-breadcrumb to list of the plugins

---

source/_data/themes.yml

Change theme wind's preview and link.

---

source/docs/commands.md

Add information about `--force` and `--bail` options.

Update documenation for generate command

---

source/_data/plugins.yml

mermaid diagrams filter for hexo

hexo-filter-mermaid-diagrams

---

source/docs/permalinks.md
source/zh-cn/docs/permalinks.md

add `post_title` for `permalink`
https://github.com/hexojs/hexo/blob/master/lib/plugins/filter/post_permalink.js#L15
`post_title` is important for permalink.

add post_title for permalink

---

source/_data/plugins.yml

add a new hexo plugin: hexo-filter-hide-content

---

source/api/filter.md

It has been introduced in hexojs/hexo#3091

Document after_clean filter

---

source/_data/plugins.yml

add a new hexo plugin: hexo-tag-color-block

---

source/_data/plugins.yml

Add Plugin: hexo-renderer-webpack4

---

source/_data/plugins.yml

Added hexo-seo-link-visualizer

---

source/_data/themes.yml

update dxx theme proview url

---

source/pt-br/api/filter.md

References:
https://github.com/hexojs/site/commit/9335c953c9cee0f613a1d9c9a2d8caeb6cbab2e0#diff-68710f4a8168ebb2b2dee8c49f6d3ee3

Update the portuguese translation

---

source/docs/helpers.md

I found a misc mistake.
Thanks.

Fix wrong description for helpers

---

source/api/index.md

Add a example for call list option

---

source/api/index.md

add Hexo draft Initialize option

---

source/_data/plugins.yml

I have search a round hexo plugins for similar feature.
And i found one, but not update for a while, and also hard to use.[Link](https://github.com/wicksome/hexo-slides-reveal)  
So i wrote a plugin, but make more feature in it.

Add plugin: hexo-generator-slidehtml

---

source/_data/plugins.yml

add hexo-renderer-ts

---

source/_data/plugins.yml

add plugins: 
hexo-plugin-permalink-pathed-title
hexo-plugin-hierarchy-category

add plugins: hexo-plugin-permalink-pathed-title, hexo-plugin-hierarchy-category

---

source/zh-cn/docs/index.md

这是中文Hexo系列教学视频的第一部, 其后的视频在制作后将依次添加.

添加Hexo简介视频

---

source/ko/docs/writing.md

edit sentence in korean writing.md

---

source/docs/index.md
source/ko/docs/index.md
source/pt-br/docs/index.md
source/ru/docs/index.md
source/zh-cn/docs/index.md
source/zh-tw/docs/index.md

* update nvm version
* specify nvm version

Update nvm install command

---

package.json

Update hexo 3.8.0

---

source/pt-br/docs/contributing.md

Change contributing.md to the display box instead of {% code%}

---

source/docs/tag-plugins.md

This PR updates the documentation after this PR will be merged. Do not merge yet 
https://github.com/hexojs/hexo/pull/3283

Updates docs for vimeo videos

---

source/_data/plugins.yml

This pull adds new plugin to the catalog, [hexo-workbox](https://www.npmjs.com/package/hexo-workbox).
Another way to manage different cache strategies using the workbox library.

add plugin: hexo-workbox

---

source/zh-cn/docs/front-matter.md

添加中文Front Matter教学视频

---

.github/PULL_REQUEST_TEMPLATE.md

Add checklist about already read a publishing document or not.
Like (#796) and (#788), contributors may not known image size rule etc...

chore(doc): add checklist to PULL_REQUEST_TEMPLATE

---

source/zh-cn/docs/commands.md
source/zh-cn/docs/configuration.md
source/zh-cn/docs/front-matter.md
source/zh-cn/docs/index.md
source/zh-cn/docs/setup.md
source/zh-cn/docs/writing.md

添加命令视频同时将视频地址从Youtube转到Bilibili

---

.eslintrc

This package is private, node/no-unpublished-required is unnecessary

---

source/_data/plugins.yml

add plugin: hexo-renderer-postcss2

---

source/_posts/2018-12-12-hexo-filter-responsive-images-1-4-0_1-4-1_hexo-asset-pipeline-1-7-0_released.md

* hexo-filter-responsive-images 1.4.0 & 1.4.1
* hexo-asset-pipeline 1.7.0

chore(news): hexo-filter-responsive-images 1.4.0, 1.4.1 & hexo-asset-pipeline 1.7.0 release news

---

themes/navy/languages/fr.yml

French translation for the theme with all the proposition from
https://github.com/hexojs/site/pull/720

 French translation for the theme #720 with proposition

---

source/_data/themes.yml

Update Clexy theme demo link

---

source/_posts/2018-12-26-hexo-autoprefixer-2-0-0_released.md

chore(news): hexo-autoprefixer 2.0.0 release news

---

source/docs/deployment.md
source/zh-cn/docs/deployment.md

1. Updated Chinese documentation in Deployment section to match with English version.
2. Minor fix and addition to English version.

Update Chinese documentation in Deployment section to match with English version

---

source/_data/themes.yml

Summary:
This pull request will update the preview url for the [Gradient](https://github.com/RandomAdversary/Gradient) theme.

Update themes.yml - new preview url for Gradient theme.

---

source/_data/plugins.yml

Update hexo-tag-bootstrap description

---

source/_data/plugins.yml

* Delete official tag from some non-official plugins
* Add official tag to some official plugins

chore(plugin): fix official plugin list

---

source/_posts/2019-01-11-hexo-deployer-git-1.0.0_released.md

chore(news): hexo-deployer-git 1.0.0 release news

---

source/_data/plugins.yml

add hexo-oembed plugin

---

source/_data/themes.yml

Update demo domain.

---

source/_data/plugins.yml

hexo-photoswipe is a fine gallery to exhibit photos in vanilla hexo blog. For more information , see github repository

add hexo-photoswipe

---

source/docs/setup.md

Fix EJS website link – former was spam

---

source/ko/docs/setup.md
source/pt-br/docs/setup.md
source/ru/docs/setup.md
source/th/docs/setup.md
source/zh-cn/docs/setup.md
source/zh-tw/docs/setup.md

fix: all language of EJS web site link

---

source/docs/helpers.md

There is no limit by default
See https://github.com/hexojs/hexo-theme-landscape/issues/12

Fix doc related to tagcloud

---

source/_data/plugins.yml

- [x ] Read the [theme publishing doc](https://hexo.io/docs/themes#Publishing) or [plugin publishing doc](https://hexo.io/docs/plugins#Publishing).
http://tnickel.de/2019/02/23/nomnoml-plugin/
Numnoml generates SVG, that SVG is then added as img-html-tag with dataURL into the website.
Tag-arguments are used to customize the img tag.

provide the nomnoml tag to embed UML

---

source/_data/themes.yml

See https://github.com/moumao/hexo-theme-Vateral/issues/39

fix demo link for vateral theme

---

source/_data/plugins.yml

add hexo-twitter-auto-publish to plugins

---

.gitignore
source/_data/themes.yml

* drop "for hexo", it's redundant
* fix some typos
* homogenize tags to help research

Cleanup theme list

---

source/_data/themes.yml

update hero-theme-xups preview url

update hero-theme-xups preview url

---

source/_data/plugins.yml

Add new plugin hexo-enhancer

---

source/_data/plugins.yml

add hexo-tag-details plugin

---

source/zh-cn/docs/commands.md
source/zh-cn/docs/configuration.md
source/zh-cn/docs/deployment.md
source/zh-cn/docs/front-matter.md
source/zh-cn/docs/index.md
source/zh-cn/docs/setup.md
source/zh-cn/docs/writing.md
source/zh-tw/docs/commands.md
source/zh-tw/docs/configuration.md
source/zh-tw/docs/deployment.md
source/zh-tw/docs/front-matter.md
source/zh-tw/docs/index.md
source/zh-tw/docs/setup.md
source/zh-tw/docs/writing.md

Update the Chinese video tutorial links

---

source/_data/plugins.yml

Add `hexo-tag-mplayer` plugin.

---

source/_data/plugins.yml

Hello! The hexo-tag-mtime plugin is embed a movie card on Hexo article.

feat: Add ‘hexo-tag-mtime’ plugin.

---

source/docs/index.md
source/pt-br/docs/index.md
source/th/docs/index.md
source/zh-tw/docs/index.md

chore: update install Node.js section

---

source/docs/front-matter.md
source/ko/docs/front-matter.md
source/pt-br/docs/front-matter.md
source/ru/docs/front-matter.md
source/th/docs/front-matter.md
source/zh-cn/docs/front-matter.md
source/zh-tw/docs/front-matter.md

chore: update front-matter

---

source/docs/commands.md

- Add options for the `new` command
- Explain the behaviour when using `--path` option

Complete the documentation for  new command

---

source/docs/contributing.md
source/ko/docs/contributing.md
source/pt-br/docs/contributing.md
source/ru/docs/contributing.md
source/th/docs/contributing.md
source/zh-cn/docs/contributing.md
source/zh-tw/docs/contributing.md

* Add official-plugin section
* Welcome message to top of the page

chore: update contributing document

---

source/_posts/2019-06-01-hexo-cli-2-0-0-released.md

chore(news): create hexo-cli 2.0.0 released news

---

source/_data/plugins.yml

add the plugin: hexo-stop-tag-plugins

---

gulpfile.js
source/_data/plugins.yml
source/_data/themes.yml
source/_posts/2014-07-13-hexo-2-8-released.md
source/ko/api/events.md
source/pt-br/api/events.md
source/ru/api/events.md
source/th/api/events.md
source/zh-cn/api/events.md
source/zh-tw/api/events.md
themes/navy/layout/partial/after_footer.swig

Lunr was not at the same version as in package.json
also there was an issue with image names with space in them
cleanup tags
fix broken links
fix typo

fix issue with lunr & theme name with space

---

source/docs/helpers.md

https://github.com/hexojs/hexo/blob/7fba3c1f667f8beb331f16776f1c7c6908d78c3c/lib/plugins/helper/is.js#L30-L32

docs: mention is_page() helper

---

source/_data/themes.yml

change Chic theme link and preview urls.

Change theme Chic link and preview urls.

---

source/_data/plugins.yml

adding hexo-tag-youtube-responsive plugin

---

source/_data/plugins.yml

Simply added a plugin in the plugin list

added strava tag plugin

---

source/docs/configuration.md
source/docs/front-matter.md
source/zh-cn/docs/configuration.md
source/zh-cn/docs/front-matter.md
source/zh-tw/docs/configuration.md
source/zh-tw/docs/front-matter.md

This PR is trying to fix #1005 
Only en, zh-CN and zh-TW version of docs have updated.

fix: add missing site config value 'keywords'

---

source/docs/configuration.md

Fixes https://github.com/hexojs/site/issues/1019
https://github.com/hexojs/hexo/pull/3653

docs: describe meta_generator option

---

source/docs/configuration.md

https://github.com/hexojs/hexo/pull/3538

docs: update globbing link

---

source/docs/configuration.md
source/ko/docs/configuration.md
source/ko/docs/helpers.md
source/ko/docs/index.md
source/pt-br/docs/configuration.md
source/pt-br/docs/helpers.md
source/pt-br/docs/index.md
source/ru/docs/configuration.md
source/ru/docs/helpers.md
source/ru/docs/index.md
source/th/docs/configuration.md
source/th/docs/helpers.md
source/th/docs/index.md
source/th/docs/setup.md
source/zh-cn/docs/configuration.md
source/zh-cn/docs/helpers.md
source/zh-cn/docs/index.md
source/zh-cn/docs/variables.md
source/zh-tw/docs/configuration.md
source/zh-tw/docs/helpers.md
source/zh-tw/docs/index.md
source/zh-tw/docs/variables.md

- Update translation of `meta_generator` configurations for zh-CN (#1020)
- Add NodeSource notes for zh-CN (#1016)
- Update nvm install command and repo url for all languages (#1018)
- Fix typo issues for all other languages (#1016)
- Update globbing link for all other languages (#1021)

docs: update translation for zh-cn & update for other languages

---

.github/PULL_REQUEST_TEMPLATE.md

chore: add checklist to PULL_REQUEST_TEMPLATE

---

source/_data/themes.yml

Updates the preview link for the Artemis theme:
https://hexo-theme-artemis.netlify.com

Update theme Artemis preview link.

---

themes/navy/layout/partial/after_footer.swig
themes/navy/layout/partial/head.swig

`cdnjs.cloudflare.com` & `maxcdn.bootstrapcdn.com` performances bad in China while jsDelivr has [good coverage](https://www.jsdelivr.com/network#china). So I have switched to jsDelivr.

feat(theme): change to jsdelivr

---

source/_data/plugins.yml

docs(plugins): update github links

---

source/docs/configuration.md
source/docs/tag-plugins.md

Add more clarifications and use clearer formatting.

Clarify docs

---

source/docs/index.md

Address https://github.com/hexojs/hexo-starter/issues/3

docs: add advanced installation and usage

---

source/docs/deployment.md

This PR adds ZEIT Now to the deployment list, allowing Hexo users to deploy their site with zero configuration and just a single command!

Add ZEIT Now Deployment Method

---

source/zh-cn/docs/deployment.md

The current translation of `deployment-git` is obscure. I have rewritten this part.
Related to #759

docs: rewrite deploy using git for zh-cn

---

source/_data/plugins.yml

- [ x] I want to publish my plugin on Hexo official website.
- [ x] I have read the [plugin publishing doc](https://hexo.io/docs/plugins#Publishing).
- [ x] `link` URL is correct.

Add hexo-renderer-babelify to the plugins list

---

source/_posts/2019-08-21-hexo-util-1-0-0_hexo-renderer-marked-2-0-0_released.md

https://github.com/hexojs/hexo-util/releases/tag/1.0.0
https://github.com/hexojs/hexo-renderer-marked/releases/tag/2.0.0

docs: hexo-util@1 & hexo-renderer-marked@2

---

source/zh-cn/docs/variables.md

Fix links to Lodash documentation and "Data Model", sync with English documentaion.

docs: update variables.md(zh-cn)

---

source/docs/asset-folders.md
source/docs/commands.md
source/docs/configuration.md
source/docs/deployment.md
source/docs/helpers.md
source/docs/troubleshooting.md

When reading the documentation, I noticed several grammar mistakes, typos and strange expressions, therefore I tried to fix some of them and opened this PR. However, I'm not a native speaker of English either, so sorry for any mistake, also, modifications and suggestions are welcome :)
PS: I think "3. More wait you to discover... :)" in the PR template should be "3. More **waiting** you to discover... :)"

docs: polish expressions and fix mistakes

---

themes/navy/source/js/toc.js

fix(toc): prevent scrolling past the footer

---

source/_posts/2019-09-07-hexo-server-1_hexo-front-matter-1_hexo-fs_2.md

news: hexo-server@1, hexo-front-matter@1, hexo-fs@2

---

source/docs/configuration.md

Closes https://github.com/hexojs/hexo-generator-index/issues/12

docs: index_generator config description

---

source/_posts/2019-09-08-hexo-i18n-1_hexo-clean-css-1_hexo-util-1-1.md

news: hexo-i18n@1, hexo-clean-css@1, hexo-util@1.1

---

source/docs/tag-plugins.md
source/zh-cn/docs/tag-plugins.md

closes #858 
@YoshinoriN @curbengh I've updated Chinese (Simplify) and English version, I'm not familiar with other languages so I can't update the corresponding versions, please help on this or merge this first and update them later :) thanks

Update docs to explain include ranged code lines

---

source/zh-cn/docs/setup.md

Fix youtube link

---

source/docs/helpers.md
source/ko/docs/helpers.md
source/ru/docs/helpers.md
source/th/docs/helpers.md
source/zh-cn/docs/helpers.md
source/zh-tw/docs/helpers.md

fix: escape single quote in text

---

source/_data/plugins.yml

Add hexo-fun-time plugin

---

source/_data/plugins.yml

plugins: add hexo-asset

---

source/_data/plugins.yml

plugins: add hexo-hide-posts

---

source/ko/docs/github-pages.md
source/pt-br/docs/github-pages.md
source/ru/docs/github-pages.md
source/th/docs/github-pages.md
source/zh-cn/docs/github-pages.md
source/zh-tw/docs/github-pages.md

https://github.com/hexojs/site/blob/3b9ef544eecf1ea65306eee95c1d5c97ca40d864/source/_data/sidebar.yml#L17
To avoid [404](https://hexo.io/zh-cn/docs/github-pages.html) for other languages, the `github-pages.md` has been copied to all the languages directories.
A zh-CN translation for GitHub Pages guide is included as well.

fix: add github-guide to all the languages to avoid 404 & bring up zh-cn translations

---

source/docs/tag-plugins.md

The examples currently are not rendered.
Noticed from https://github.com/hexojs/site/pull/1102

fix: post_link examples

---

source/_data/menu.yml
source/about/index.md
themes/navy/languages/de.yml
themes/navy/languages/en.yml
themes/navy/languages/fr.yml
themes/navy/languages/ko.yml
themes/navy/languages/pt-br.yml
themes/navy/languages/ru.yml
themes/navy/languages/th.yml
themes/navy/languages/zh-cn.yml
themes/navy/languages/zh-tw.yml

site(about): add to menu, add opencollective and stats badges

---

source/ko/docs/index.md
source/pt-br/docs/index.md
source/ru/docs/index.md
source/th/docs/index.md
source/zh-cn/docs/index.md
source/zh-tw/docs/index.md

docs: update nvm syntax for all languages

---

source/index.jade

This is mainly to highlight hexo plugin system and give example packages that are well-known to web devs.

site: update Plugins section

---

source/_posts/2019-09-27-warehouse-3_hexo-util-1-3-1.md

news: warehouse 3.0.0 & hexo-util 1.3.1

---

source/zh-cn/docs/github-pages.md

Any issue regarding unclear instruction should be raised in Issues or PRs, and productively discussed.

docs(github-pages): remove unnecessary note in zh-cn translation

---

source/docs/github-pages.md

docs(gh-pages): mention hexo deploy

---

source/_data/themes.yml

my preview link has been expired and need to be replaced

Fix:  preview link has been expired and need to be replaced

---

.github/PULL_REQUEST_TEMPLATE.md

As a transitory measure for #1114

chore: update PULL_REQUEST_TEMPLATE

---

themes/navy/source/css/_partial/sidebar.styl

theme(sidebar): fix TOC word-break

---

source/docs/index.md
source/ko/docs/index.md
source/pt-br/docs/index.md
source/ru/docs/index.md
source/th/docs/index.md
source/zh-cn/docs/index.md
source/zh-tw/docs/index.md

Mention [nvs](https://github.com/jasongin/nvs) in installation guide.
Travis CI currently use nvs in their Windows Build Enviroment.

docs(install): mention nvs for windows

---

source/th/docs/tag-plugins.md
source/zh-cn/docs/tag-plugins.md

docs: update post link examples

---

source/zh-cn/index.jade
themes/navy/languages/zh-cn.yml

docs: update translation for zh-cn

---

source/about/index.md
themes/navy/layout/partial/share.swig

- Use https://shields.io to load GitHub star/fork & Twitter follow button, which is lighter and could work without external js.
- Add NPM Downloads badge to the index
- Add GitHub Fork badge to about page

refactor: update badges

---

source/docs/github-pages.md
source/ko/docs/github-pages.md
source/pt-br/docs/github-pages.md
source/ru/docs/github-pages.md
source/zh-cn/docs/github-pages.md
source/zh-tw/docs/github-pages.md

docs(gh-pages): simplify private repo guide

---

scripts/responsive.js

I feel `hasOwnProperty` is more proper than `if (updatePng[value])`.
also hoist the condition to the top for reduced condition checking and more specific `replace()`.

refactor: use Object.hasOwnProperty

---

source/zh-cn/docs/commands.md
source/zh-cn/docs/configuration.md
source/zh-cn/docs/front-matter.md
source/zh-cn/docs/index.md
source/zh-cn/docs/one-command-deployment.md
source/zh-cn/docs/setup.md
source/zh-cn/docs/writing.md
source/zh-tw/docs/commands.md
source/zh-tw/docs/configuration.md
source/zh-tw/docs/front-matter.md
source/zh-tw/docs/index.md
source/zh-tw/docs/one-command-deployment.md
source/zh-tw/docs/setup.md
source/zh-tw/docs/writing.md

Update Youtube Links for Chinese Tutorial

---

source/_posts/2019-10-09-hexo-cli-3_hexo-util-1-4.md

news: hexo-cli 3.0.0 & hexo-util 1.4.0 released

---

package.json

Hexo.io has hundreds of external links, we can't continuously monitor all of them.

build: add hexo-filter-nofollow

---

source/api/filter.md

docs(filter_api): recommend configurable priority value

---

themes/navy/layout/index.swig
themes/navy/source/css/_partial/index.styl

feat(index): add recent news

---

source/api/filter.md
source/ko/api/filter.md
source/pt-br/api/filter.md
source/ru/api/filter.md
source/th/api/filter.md
source/zh-cn/api/filter.md
source/zh-tw/api/filter.md

docs(filter): add examples of unregister

---

source/_data/plugins.yml

- [1] I want to publish my plugin on Hexo official website.
- [1] I have read the [plugin publishing doc](https://hexo.io/docs/plugins#Publishing).
- [1] `name` is unique.
- [1] `link` URL is correct.

added hexo-auto-link-checker plugin

---

source/docs/github-pages.md
source/ko/docs/github-pages.md
source/pt-br/docs/github-pages.md
source/th/docs/github-pages.md

Fix typo, GitHub instead of GitLab

---

themes/navy/languages/de.yml
themes/navy/languages/en.yml
themes/navy/languages/fr.yml
themes/navy/languages/ko.yml
themes/navy/languages/pt-br.yml
themes/navy/languages/ru.yml
themes/navy/languages/th.yml
themes/navy/languages/zh-cn.yml
themes/navy/languages/zh-tw.yml
themes/navy/layout/index.swig
themes/navy/source/css/_partial/index.styl

feat(index): add theme section

---

source/docs/index.md

Addresses https://github.com/hexojs/site/pull/1137#issuecomment-538716437, cc @SukkaW 
I tested nvs; the [official guide](https://github.com/jasongin/nvs) mentions installing to home folder, which means global npm packages are also installed there, so shouldn't have permission issue (I didn't experience any).

docs(installation): prioritize official installer and recommends nvs/nvm

---

themes/navy/source/css/_partial/index.styl

Notice this while testing hexo-renderer-pug
Either color-default (`#444`) or black.

site(index): use existing variable for theme-link:hover

---

themes/navy/layout/partial/footer.swig

to fulfill netlify open source plan [policy](https://www.netlify.com/legal/open-source-policy/).

site(footer): add netlify logo

---

source/zh-cn/docs/configuration.md

docs: add pretty_urls.trailing_index for zh-cn

---

source/docs/commands.md
source/zh-cn/docs/commands.md

add hexo generate --concurrency option

---

source/docs/configuration.md

https://github.com/hexojs/hexo/pull/3691

docs: add pretty_urls.trailing_index option

---

source/docs/helpers.md
source/zh-cn/docs/helpers.md

https://github.com/hexojs/hexo-util/pull/84
https://github.com/hexojs/hexo/pull/3701
Add usage & example for newly added `full_url_for()` helper.
Should be merged after hexo 4 is released.

docs(helper): add full_url_for

---

source/docs/front-matter.md
source/docs/tag-plugins.md

Feature introduced through https://github.com/hexojs/hexo/pull/3612
Closes #1007 

docs: page excerpt using front matter

---

source/docs/configuration.md
source/ko/docs/configuration.md
source/pt-br/docs/configuration.md
source/ru/docs/configuration.md
source/th/docs/configuration.md
source/zh-cn/docs/configuration.md
source/zh-tw/docs/configuration.md

docs: new external_link config

---

source/docs/variables.md

https://github.com/hexojs/hexo/pull/3708

docs: site.url, page.permalink & post.permalink are url-encoded

---

source/zh-cn/docs/helpers.md

docs: more details to url_for, relative_url & gravatar for zh_cn

---

source/docs/configuration.md
source/ko/docs/configuration.md
source/pt-br/docs/configuration.md
source/ru/docs/configuration.md
source/th/docs/configuration.md
source/zh-cn/docs/configuration.md
source/zh-tw/docs/configuration.md

+ some missing doc in other languages (highlight.*)
To fix #1097

Document use_date_for_updated

---

source/_posts/2019-10-19-hexo-renderer-jade-0-5_hexo-renderer-pug-1.md

news: hexo-renderer-jade 0.5.0 & hexo-renderer-pug 1.0.0

---

source/docs/helpers.md
source/ko/docs/helpers.md
source/pt-br/docs/helpers.md
source/ru/docs/helpers.md
source/th/docs/helpers.md
source/zh-cn/docs/helpers.md
source/zh-tw/docs/helpers.md

docs: Add escape parameter to `paginator`.

---

source/_data/plugins.yml

Add hexo-tag-abcjs for rendering abc notation

---

source/_data/plugins.yml

add 'hexo-unique-post-path' plugin

---

source/docs/tag-plugins.md
source/ko/docs/tag-plugins.md
source/pt-br/docs/tag-plugins.md
source/ru/docs/tag-plugins.md
source/th/docs/tag-plugins.md
source/zh-cn/docs/tag-plugins.md
source/zh-tw/docs/tag-plugins.md

Closes: #1098
Related: #1102, #1152
```diff
- {% post_link hexo-3-9-released 'How to use <b> tag in title' %}
+ {% post_link hexo-4-released 'How to use <b> tag in title' %}
```

update links of sample codes of 'post_link' plugin

---

source/_data/plugins.yml

add hexo-plugin-gitalk and hexo-plugin-readmore

---

source/_posts/2019-11-10-hexo-generator-feed-2-1_hexo-util-1-5.md

news: hexo-generator-feed 2.1.0 & hexo-util 1.5.0

---

source/docs/permalinks.md
source/ko/docs/permalinks.md
source/pt-br/docs/permalinks.md
source/ru/docs/permalinks.md
source/th/docs/permalinks.md
source/zh-cn/docs/permalinks.md
source/zh-tw/docs/permalinks.md

fix: permalink example

---

source/docs/one-command-deployment.md

`token` option is introduced in https://github.com/hexojs/hexo-deployer-git/pull/135
https://github.com/hexojs/hexo-deployer-git/pull/151#issuecomment-552089551

docs(deploy): token config of hexo-deployer-git

---

source/_posts/2019-11-22-hexo-deployer-git-2-1_hexo-generator-feed-2-1-1_hexo-generator-sitemap-2.md

news: hexo-deployer-git 2.1, hexo-generator-feed 2.1.1 & hexo-generator-sitemap 2.0

---

source/_posts/2019-11-28-hexo-util1-6_hexo-generator-feed-2-2_hexo-uglify-1-1.md

hexo-uglify 1.0.0 wasn't announced previously.

news: hexo-util 1.6,hexo-generator-feed 2.2,hexo-uglify 1.1

---

source/docs/one-command-deployment.md
source/ko/docs/one-command-deployment.md
source/pt-br/docs/one-command-deployment.md
source/ru/docs/one-command-deployment.md
source/th/docs/one-command-deployment.md
source/zh-cn/docs/one-command-deployment.md
source/zh-tw/docs/one-command-deployment.md

Continuation of https://github.com/hexojs/site/pull/1212

docs(deploy+langs): token config of hexo-deployer-git

---

source/_data/plugins.yml

Added hexo-simple-image plugins.

---

source/_data/plugins.yml

plugin: hexo-easy-tags-plugin

---

source/_data/plugins.yml

plugin: hexo-git-username-coauthor

---

source/_data/plugins.yml

add plugin: hexo-deployer-qiniucloud2

---

source/docs/helpers.md
source/ko/docs/helpers.md
source/pt-br/docs/helpers.md
source/ru/docs/helpers.md
source/th/docs/helpers.md
source/zh-cn/docs/helpers.md
source/zh-tw/docs/helpers.md

https://github.com/hexojs/hexo/pull/3782
Required before addressing https://github.com/hexojs/hexo/commit/651f34bf6d2be5cb9c07009e857a73ecad3b414c#r35985975

docs(helpers): add meta_generator()

---

source/_posts/2019-12-09-hexo-4-1-released.md

news: hexo 4.1.0

---

source/docs/helpers.md
source/ko/docs/helpers.md
source/pt-br/docs/helpers.md
source/ru/docs/helpers.md
source/th/docs/helpers.md
source/zh-cn/docs/helpers.md
source/zh-tw/docs/helpers.md

https://github.com/hexojs/hexo/pull/3681
https://github.com/hexojs/hexo/pull/3690

docs(css/js): custom attributes

---

source/docs/configuration.md
source/docs/tag-plugins.md
source/ko/docs/configuration.md
source/ko/docs/tag-plugins.md
source/pt-br/docs/configuration.md
source/pt-br/docs/tag-plugins.md
source/ru/docs/configuration.md
source/ru/docs/tag-plugins.md
source/th/docs/configuration.md
source/th/docs/tag-plugins.md
source/zh-cn/docs/configuration.md
source/zh-cn/docs/tag-plugins.md
source/zh-tw/docs/configuration.md
source/zh-tw/docs/tag-plugins.md

Introduced in https://github.com/hexojs/hexo/pull/3827 https://github.com/hexojs/hexo/pull/2901

docs(config): add wrap and hljs to 'highlight' options

---

source/docs/configuration.md
source/ko/docs/configuration.md
source/pt-br/docs/configuration.md
source/ru/docs/configuration.md
source/th/docs/configuration.md
source/zh-cn/docs/configuration.md
source/zh-tw/docs/configuration.md

https://github.com/hexojs/hexo/pull/3917

docs: pretty_urls.trailing_html

---

.travis.yml

ci(travis): remove deprecated sudo option

---

_config.yml

https://github.com/hexojs/hexo/pull/3917

build: disable pretty_urls.trailing_html

---

source/_posts/2019-12-12-hexo-4-1-1_hexo-util-1-7_eslint-config-hexo-4.md

news: Hexo 4.1.1, hexo-util 1.7.0 & eslint-config-hexo 4.0.0

---

source/_posts/2019-12-15-hexo-renderer-markdown-it-4.md

news: hexo-renderer-markdown-it v4

---

source/_data/plugins.yml

Add hexo-tag-wikipedia to plugins.yml

---

source/_data/plugins.yml

add hexo-images-watermark plugin

---

source/docs/helpers.md
source/ko/docs/helpers.md
source/pt-br/docs/helpers.md
source/ru/docs/helpers.md
source/th/docs/helpers.md
source/zh-cn/docs/helpers.md
source/zh-tw/docs/helpers.md

The feature is introduced in https://github.com/hexojs/hexo/pull/3997 and this PR should supersede #1246.

docs(helper): min_depth option for toc()

---

source/_posts/2019-12-22-hexo-4.2-released.md
source/_posts/2019-12-22-hexo-4.2_hexo-util-1-8_eslint-config-hexo-released.md

news: Hexo 4.2.0 released

---

source/_posts/2019-12-15-hexo-renderer-markdown-it-4.md

news(markdown-it-plugin): add version number to title

---

source/zh-cn/docs/variables.md

total 为总页数

---

source/_data/plugins.yml

Add hexo-tag-mmedia to plugins.yml

---

.github/PULL_REQUEST_TEMPLATE.md

add languages checklist

---

source/_data/themes.yml

chore: fix theme preview

---

source/zh-cn/docs/contributing.md

Translate more strings

---

source/_data/plugins.yml

plugin: hexo-tag-photozoom

---

source/_data/plugins.yml

plugin: hexo-bilibili-bangumi

---

source/docs/helpers.md
source/ko/docs/helpers.md
source/pt-br/docs/helpers.md
source/ru/docs/helpers.md
source/th/docs/helpers.md

doc: fix translation inconsistency

---

source/_data/plugins.yml

* add plugin hexo-deployer-cos-cdn
- Languages:

add plugin hexo-deployer-cos-cdn

---

source/_data/plugins.yml

The plug-in adds support for Alibaba cloud object storage service and CDN refresh.
Synchronization update plug-in description.

Update plugin hexo-deployer-cos-cdn

---

source/_data/plugins.yml

plugin: hexo-online-server

---

source/_data/plugins.yml

add hexo-web-push-notification to plugin list

---

source/docs/permalinks.md
source/ko/docs/permalinks.md
source/pt-br/docs/permalinks.md
source/ru/docs/permalinks.md
source/th/docs/permalinks.md
source/zh-cn/docs/permalinks.md
source/zh-tw/docs/permalinks.md

- Languages:
Issue resolved: https://github.com/hexojs/hexo/issues/2650, https://github.com/theme-next/hexo-theme-next/issues/471

docs(permalinks): add trailing slash

---

source/_data/plugins.yml

Adding hexo-cldnry plugin.

---

scripts/responsive.js
source/_data/plugins.yml

plugin: hexo-tag-steamgame

---

source/_data/themes.yml

Update theme's preview URL

---

source/_data/themes.yml

Change the name and url of my theme

---

source/zh-cn/docs/configuration.md

docs: add recommended config of language to zh-cn

---

netlify.toml

The redirect behavior will be changed since April 7th. Redirects without the forced rules will not work if the file exists for a given path. This pull request adds `force = true` to all `redirects` in `netlify.toml`.
https://community.netlify.com/t/changed-behavior-in-redirects/10084/16
https://docs.netlify.com/configure-builds/file-based-configuration/#redirects
- Languages:

Set force=true to all redirects in netlify.toml

---

source/_data/plugins.yml

add the hexo-deployer-tcb plugins

add the hexo-deployer-tcb plugins

---

source/_data/plugins.yml

add plugin hexo-deployer-clodui

---

source/_data/plugins.yml

add plugin hexo-admonition.
- Languages:

add plugin hexo-admonition

---

source/zh-cn/docs/one-command-deployment.md

Add 21yunbox for deployment
- Languages:

docs: add 21yunbox for deployment

---

scripts/helpers.js
themes/navy/layout/plugins.swig

- Languages:
Drop usage of lodash. Sort theme & plugin randomly so that people won't use `A` prefixed name again.

refactor: random sort theme & plugin

---

source/_data/plugins.yml

hexo-broken-links-checker added

---

source/_data/themes.yml

Update preview link according to coding.net service upgrade.

update hexo-theme-autumn preview link

---

source/_data/themes.yml

This PR will update the links for the Gradient theme.
- Languages:

Update links for Gradient theme.

---

source/_data/themes.yml

Remove 404 link

---

source/_data/plugins.yml

hexo-html-prettify

---

source/_data/plugins.yml

plugin: hexo-statistics-charts

---

source/_data/themes.yml

change the theme hiya's preview link

---

source/_data/plugins.yml

Check [here](https://github.com/TimDaub/hexo-compat-report#use-case) for more information.
Thanks for creating hexo. I really like it 👍

Add plugin: hexo-compat-report

---

source/_data/plugins.yml

plugin: hexo-lute

---

scripts/helpers.js
themes/navy/layout/partial/plugin.swig
themes/navy/layout/partial/theme.swig
themes/navy/source/js/plugins.js

Users report that lunr search is not working, because search index is not updated during random sorting.
Ref:
https://github.com/hexojs/site/pull/1424#issuecomment-630164523
https://github.com/hexojs/site/pull/1397#issuecomment-619421220
https://github.com/hexojs/site/pull/1390

Fix lunr search

---

source/docs/helpers.md
source/ko/docs/helpers.md
source/pt-br/docs/helpers.md
source/ru/docs/helpers.md
source/th/docs/helpers.md
source/zh-cn/docs/helpers.md
source/zh-tw/docs/helpers.md

helpers: more details about render()

---

source/_data/plugins.yml

add new plugin - hexo-generator-podcasts

---

package.json
scripts/validate.js

Validate Themes' thumbnails before generation

---

source/_data/plugins.yml

plugin: hexo-filter-mathjax and hexo-pangu

---

themes/navy/source/css/_partial/page.styl

- Languages:
**Before**
**After**

fix(content): large table overflow

---

themes/navy/source/css/_partial/mobile_nav.styl

- Languages:
**Before**
**After**

fix(mobile-nav): avoid content overflow

---

source/_data/themes.yml

update butterfly demo link,description and tags

---

source/_posts/2020-06-27-hexo-marked-3_migrator-wordpress-2_migrator-rss-1.md

news: hexo-renderer-marked 3.0.0, hexo-migrator-wordpress 2.0.0 & hexo-migrator-rss 1.0.0

---

source/ru/docs/gitlab-pages.md

Грамматические правки / Grammatical edits

---

source/_data/plugins.yml

change hexo-images-watermark link
Migrate new repository
迁移新仓库
- Languages:

change hexo-images-watermark link

---

source/_data/plugins.yml

Hexo plugin to submit URLs of new posts to Google, Bing, Baidu search engine to improve the quality and speed of website collection.
https://github.com/cjh0613/hexo-submit-urls-to-search-engine

Hexo plugin to submit URLs of new posts to Google, Bing, Baidu search engine to improve the quality and speed of website collection

---

source/docs/configuration.md
source/docs/front-matter.md
source/ko/docs/configuration.md
source/pt-br/docs/configuration.md
source/ru/docs/configuration.md
source/th/docs/configuration.md
source/zh-cn/docs/configuration.md
source/zh-cn/docs/front-matter.md
source/zh-tw/docs/configuration.md
source/zh-tw/docs/front-matter.md

also drop comma-separated keywords
Closes #1286 
https://github.com/hexojs/hexo/pull/4174
- Languages:

docs: drop keywords from front-matter

---

source/_data/plugins.yml

publish 2 plugins

---

source/docs/tag-plugins.md
source/ko/docs/tag-plugins.md
source/pt-br/docs/tag-plugins.md
source/ru/docs/tag-plugins.md
source/th/docs/tag-plugins.md
source/zh-cn/docs/tag-plugins.md
source/zh-tw/docs/tag-plugins.md

Closes https://github.com/hexojs/site/issues/1342
- Languages:

docs: youtube playlist and nocookie

---

source/docs/helpers.md
source/ko/docs/helpers.md
source/pt-br/docs/helpers.md
source/ru/docs/helpers.md
source/th/docs/helpers.md
source/zh-cn/docs/helpers.md
source/zh-tw/docs/helpers.md

issue: https://github.com/hexojs/hexo/issues/4058
pr: https://github.com/hexojs/hexo/pull/4059
- Languages:

list_tags: custom class for each element

---

source/docs/helpers.md
source/ko/docs/helpers.md
source/pt-br/docs/helpers.md
source/ru/docs/helpers.md
source/th/docs/helpers.md
source/zh-cn/docs/helpers.md
source/zh-tw/docs/helpers.md

See also https://github.com/hexojs/hexo/pull/4370
- Languages:

docs(tagcloud): new option class & level

---

source/docs/index.md
source/ko/docs/index.md
source/pt-br/docs/index.md
source/ru/docs/index.md
source/th/docs/index.md
source/zh-cn/docs/index.md
source/zh-tw/docs/index.md

docs(install): required node.js version

---

source/docs/variables.md
source/ko/docs/variables.md
source/pt-br/docs/variables.md
source/ru/docs/variables.md
source/th/docs/variables.md
source/zh-cn/docs/variables.md
source/zh-tw/docs/variables.md

docs(variables): drop lodash

---

source/_data/sidebar.yml
source/docs/syntax-highlight.md
source/ko/docs/syntax-highlight.md
source/pt-br/docs/syntax-highlight.md
source/ru/docs/syntax-highlight.md
source/th/docs/syntax-highlight.md
source/zh-cn/docs/syntax-highlight.md
source/zh-tw/docs/syntax-highlight.md
themes/navy/languages/de.yml
themes/navy/languages/en.yml
themes/navy/languages/fr.yml
themes/navy/languages/ko.yml
themes/navy/languages/pt-br.yml
themes/navy/languages/ru.yml
themes/navy/languages/th.yml
themes/navy/languages/zh-cn.yml
themes/navy/languages/zh-tw.yml

docs(highlight): bring up

---

source/docs/configuration.md
source/ko/docs/configuration.md
source/pt-br/docs/configuration.md
source/ru/docs/configuration.md
source/th/docs/configuration.md
source/zh-cn/docs/configuration.md
source/zh-tw/docs/configuration.md

- Languages:
https://github.com/hexojs/hexo/pull/4278

docs(configuration): add updated_option

---

source/_data/plugins.yml

docs(plugin): add a new plugin hexo-image-cloudflare

---

source/api/filter.md
source/api/tag.md
source/ko/api/filter.md
source/ko/api/tag.md
source/pt-br/api/filter.md
source/pt-br/api/tag.md
source/ru/api/filter.md
source/ru/api/tag.md
source/th/api/filter.md
source/th/api/tag.md
source/zh-cn/api/filter.md
source/zh-cn/api/tag.md
source/zh-tw/api/filter.md
source/zh-tw/api/tag.md

docs(api/tags & filter): examples to access user config

---

source/docs/permalinks.md
source/ko/docs/permalinks.md
source/pt-br/docs/permalinks.md
source/ru/docs/permalinks.md
source/th/docs/permalinks.md
source/zh-cn/docs/permalinks.md
source/zh-tw/docs/permalinks.md

https://github.com/hexojs/hexo/pull/4185
- Languages:

docs(permalink): ':second' variable

---

source/_data/plugins.yml

plugin: hexo-patch-load-highlight-style

---

source/_data/plugins.yml

Add plugin: hexo-calendar

---

source/_posts/2020-08-02-cli-4_wordpress-2-1_sitemap-2-1.md

- hexo-cli 4.1.0, hexo-migrator-wordpress 2.1.0, hexo-migrator-rss 1.1.0 & hexo-generator-sitemap 2.1.0
- Languages:

news: minor release of plugins

---

source/api/tag.md
source/ko/api/tag.md
source/pt-br/api/tag.md
source/ru/api/tag.md
source/th/api/tag.md
source/zh-cn/api/tag.md
source/zh-tw/api/tag.md

https://github.com/hexojs/hexo/pull/4046
- Languages:

docs(api/tag): unregister()

---

themes/navy/source/css/_partial/highlight.styl

https://github.com/hexojs/site/pull/1499#issuecomment-669740370
- Languages:

fix(css): add .marked style

---

themes/navy/source/css/_partial/highlight.styl

for `diff` codeblock.
<pre><code>``` diff
- foo
+ bar
```</code></pre>
Colors based on https://github.com/primer/github-syntax-light.

fix(css): add .deletion and .addition styles

---

source/docs/github-pages.md

Free for public and private repository.
Supersedes https://github.com/hexojs/site/pull/1343
- Languages:

docs(gh-pages): switch Travis to GH Actions

---

source/docs/helpers.md
source/ko/docs/helpers.md
source/pt-br/docs/helpers.md
source/ru/docs/helpers.md
source/th/docs/helpers.md
source/zh-cn/docs/helpers.md
source/zh-tw/docs/helpers.md

Closes https://github.com/hexojs/site/issues/1269
- Languages:

docs(helpers/feed_tag): add examples

---

source/docs/permalinks.md
source/ko/docs/permalinks.md
source/pt-br/docs/permalinks.md
source/ru/docs/permalinks.md
source/th/docs/permalinks.md
source/zh-cn/docs/permalinks.md
source/zh-tw/docs/permalinks.md

Closes https://github.com/hexojs/site/issues/1259
`:hash` https://github.com/hexojs/hexo/pull/3922
- Languages:

docs(permalinks): add :name, :post_title & :hash

---

source/docs/commands.md
source/ko/docs/commands.md
source/pt-br/docs/commands.md
source/ru/docs/commands.md
source/th/docs/commands.md
source/zh-cn/docs/commands.md
source/zh-tw/docs/commands.md

User may be curious about how `init` works and may prefer to manual initialization.
`Yarn 1` is mentioned here to implicitly mention that Yarn 2 is not supported (#1370).
- Languages:

docs(commands): background of init

---

source/api/helper.md
source/ko/api/helper.md
source/pt-br/api/helper.md
source/ru/api/helper.md
source/th/api/helper.md
source/zh-cn/api/helper.md
source/zh-tw/api/helper.md

Extension of https://github.com/hexojs/site/pull/1485
- Languages:

docs(api/helper): add usage example inside another helper

---

source/docs/configuration.md
source/docs/syntax-highlight.md
source/ko/docs/configuration.md
source/ko/docs/syntax-highlight.md
source/pt-br/docs/configuration.md
source/pt-br/docs/syntax-highlight.md
source/ru/docs/configuration.md
source/ru/docs/syntax-highlight.md
source/th/docs/configuration.md
source/th/docs/syntax-highlight.md
source/zh-cn/docs/configuration.md
source/zh-cn/docs/syntax-highlight.md
source/zh-tw/docs/configuration.md
source/zh-tw/docs/syntax-highlight.md

docs(configuration): add prismjs

---

source/_data/plugins.yml

plugin: hexo-extend-theme

---

source/_data/plugins.yml

Add New SocialShare Plugin hexo-social9-socialshare
- Languages:

Add Plugin hexo-social9-socialshare

---

source/docs/troubleshooting.md
source/ko/docs/troubleshooting.md
source/pt-br/docs/troubleshooting.md
source/ru/docs/troubleshooting.md
source/th/docs/troubleshooting.md
source/zh-cn/docs/troubleshooting.md
source/zh-tw/docs/troubleshooting.md

Encounter this issue when troubleshooting https://github.com/hexojs/hexo/issues/4485.
Credit: https://ro-che.info/articles/2017-03-26-increase-open-files-limit#systemd
- Languages:

docs(troubleshooting): overriding ulimit

---

source/docs/tag-plugins.md
source/ko/docs/tag-plugins.md
source/pt-br/docs/tag-plugins.md
source/ru/docs/tag-plugins.md
source/th/docs/tag-plugins.md
source/zh-cn/docs/tag-plugins.md
source/zh-tw/docs/tag-plugins.md

https://github.com/hexojs/hexo/issues/4473 https://github.com/hexojs/hexo/issues/3321 https://github.com/hexojs/hexo/issues/2821
- Languages:

docs(tag-plugins): tag plugin cannot be used inside markdown

---

source/docs/one-command-deployment.md
source/ko/docs/one-command-deployment.md
source/pt-br/docs/one-command-deployment.md
source/ru/docs/one-command-deployment.md
source/th/docs/one-command-deployment.md
source/zh-cn/docs/one-command-deployment.md
source/zh-tw/docs/one-command-deployment.md

Hello from the Vercel team!
Just submitting an update to the [Vercel section](https://hexo.io/docs/one-command-deployment#ZEIT-Now) in the one-command deployment doc. Unfortunately, I could only update the English version.
- Languages:

Update Vercel deployment guide

---

source/_data/plugins.yml

Add Inferno.js JSX renderer

---

source/docs/one-command-deployment.md
source/ko/docs/one-command-deployment.md
source/pt-br/docs/one-command-deployment.md
source/ru/docs/one-command-deployment.md
source/th/docs/one-command-deployment.md
source/zh-cn/docs/one-command-deployment.md
source/zh-tw/docs/one-command-deployment.md

Hello there!
I have updated the one-command deployment doc to include a guide on how to deploy to [Bip](https://bip.sh).
Unfortunately I was unable to translate the guide into the other supported languages. Looking at a similar documentation PR raised yesterday, having followed their lead, I have copied the text to the other languages. I hope that's OK.
- Languages:

Added Bip deployment guide

---

source/_posts/2019-12-09-hexo-4-1-released.md
source/_posts/2019-12-12-hexo-4-1-1_hexo-util-1-7_eslint-config-hexo-4.md
source/docs/configuration.md
source/docs/tag-plugins.md
source/ko/docs/tag-plugins.md
source/pt-br/docs/tag-plugins.md
source/ru/docs/tag-plugins.md
source/th/docs/tag-plugins.md
source/zh-cn/docs/configuration.md
source/zh-cn/docs/tag-plugins.md
source/zh-tw/docs/tag-plugins.md

- Languages:
We should stop to use `yoursite.com`.
`yoursite.com` is a real company's domain.
We can use `example.com` instead of `yoursite.com`.
> [Reserved Example Second Level Domain Names](https://tools.ietf.org/html/rfc2606#section-3)
Thank you :)

chore: use example.com for example domain

---

source/_data/plugins.yml

- Languages:
Update link and tags for hexo-renderer-inferno since it has been transferred to @hexojs.

Update link and tags for hexo-renderer-inferno

---

source/_data/themes.yml

Update preview address
- Languages:

Update preview address

---

source/_posts/2020-09-04-alias-1_cli-4-2_front-matter-2_feed-3.md

news: hexo-generator-alias 1.0.0, hexo-cli 4.2.0, hexo-front-matter 2.0.0 & hexo-generator-feed 3.0.0

---

source/_data/plugins.yml

- [+] I want to publish my plugin on Hexo official website.
- [+] I have read the [plugin publishing doc](https://hexo.io/docs/plugins#Publishing).
- [+] `name` is unique.
- [+] `link` URL is correct.
- Languages:

Add plugin hexo-collaps

---

source/docs/front-matter.md
source/docs/troubleshooting.md
source/ko/docs/front-matter.md
source/ko/docs/troubleshooting.md
source/pt-br/docs/front-matter.md
source/pt-br/docs/troubleshooting.md
source/ru/docs/front-matter.md
source/ru/docs/troubleshooting.md
source/th/docs/front-matter.md
source/th/docs/troubleshooting.md
source/zh-cn/docs/front-matter.md
source/zh-cn/docs/troubleshooting.md
source/zh-tw/docs/front-matter.md
source/zh-tw/docs/troubleshooting.md

docs(front-matter): disableNunjucks

---

source/docs/contributing.md
source/ko/docs/contributing.md
source/pt-br/docs/contributing.md
source/ru/docs/contributing.md
source/th/docs/contributing.md
source/zh-cn/docs/contributing.md
source/zh-tw/docs/contributing.md

- Add code of conduct
- Add eslint-config-hexo

docs: update contributing guide

---

source/_data/plugins.yml

plugin: hexo-widget-tree

---

source/docs/front-matter.md
source/docs/writing.md
source/ko/docs/front-matter.md
source/ko/docs/writing.md
source/pt-br/docs/front-matter.md
source/pt-br/docs/writing.md
source/ru/docs/front-matter.md
source/ru/docs/writing.md
source/th/docs/front-matter.md
source/th/docs/writing.md
source/zh-cn/docs/front-matter.md
source/zh-cn/docs/writing.md
source/zh-tw/docs/front-matter.md
source/zh-tw/docs/writing.md

Recently tried out `layout: false` (to compare with https://github.com/hexojs/hexo/pull/4435). the docs currently mention "If you don't want your posts processed...", which implies that article will be skipped. actually, the article will still be rendered (.md -> .html) and generated (shows up in index page), but not processed with a theme's layout.
- Languages:

docs(layout): mention effect of disabling layout

---

source/_data/themes.yml

I changed the demo website to another.
- Languages:

theme: Love

---

source/ru/docs/writing.md

Add ru translation for some sections of writing.md

---

source/docs/helpers.md
source/ko/docs/helpers.md
source/pt-br/docs/helpers.md
source/ru/docs/helpers.md
source/th/docs/helpers.md
source/zh-cn/docs/helpers.md
source/zh-tw/docs/helpers.md

document https://github.com/hexojs/hexo/pull/4578
- Languages:

list_tags: span element & custom class for label

---

source/_posts/2020-12-17-hexo-5-3-released.md

related to https://github.com/hexojs/hexo/pull/4575
- Languages:

chore(news): hexo 5.3.0 released

---

source/docs/helpers.md
source/ko/docs/helpers.md
source/pt-br/docs/helpers.md
source/ru/docs/helpers.md
source/th/docs/helpers.md
source/zh-cn/docs/helpers.md
source/zh-tw/docs/helpers.md

related to https://github.com/hexojs/hexo/pull/4581
- Languages:

chore(docs): add escape_html doc

---

source/zh-cn/docs/contributing.md

docs(contributing): fix typo

---

source/_data/plugins.yml

plugin: hexo-next-pwa 

---

source/_posts/2021-02-11-hexo-deployer-git-3-0-0-hexo-renderer-marked-4-0-0-released.md

refs: 
> https://github.com/hexojs/hexo-renderer-marked/releases/tag/4.0.0
> https://github.com/hexojs/hexo-deployer-git/releases/tag/3.0.0
- Languages:

chore(news): hexo-deployer-git 3.0.0, hexo-renderer-marked 4.0.0 released

---

source/_posts/2021-02-21-hexo-5-4-0-released.md

refs: https://github.com/hexojs/hexo/releases/tag/5.4.0
- Languages:

chore(news): hexo 5.4.0 released

---

scripts/helpers.js

- Languages:
If the plugins are arranged in order, it is easier for users to find the plugins they need.
Because there are many grouped by type e.g. `hexo-tag-*` `hexo-helper-*` `hexo-generator-*` `hexo-renderer-*`
https://github.com/hexojs/site/pull/1390#issuecomment-783185023

refactor: don't random sort plugin

---

source/_data/plugins.yml

Add plugin hexo-kotlin-playground

---

source/docs/front-matter.md
source/ko/docs/front-matter.md
source/pt-br/docs/front-matter.md
source/ru/docs/front-matter.md
source/th/docs/front-matter.md
source/zh-cn/docs/front-matter.md
source/zh-tw/docs/front-matter.md

add lang front-matter

---

source/_data/themes.yml

update butterfly preview link
- Languages:

update butterfly preview link

---

source/_data/plugins.yml

I have created a plugin that allows text *within a post* to be excluded from the production version of a site, but still be displayed when running in draft mode. It uses a "draft" tag plugin to mark the text that should be excluded.
eg.
```markdown
This text should be shown in --draft mode and in production.
{% draft %}
This text should only be shown in --draft mode.
{% enddraft %}
```
This PR should include the plugin in the list of published plugins on the Hexo website.
- Languages:

Add plugin: hexo-draft-tags

---

source/_data/plugins.yml

Add plugin: hexo-simpleIcons

---

source/_data/plugins.yml

Add hexo-plausible-analytics plugin

---

source/_data/plugins.yml

Added hexo-sponsor-button to plugins list

---

source/zh-cn/docs/commands.md

docs: zh-cn translation of commands

---

source/zh-cn/docs/configuration.md

docs: fix zh-cn 'configuration.md' translate issues

---

source/_data/plugins.yml

Add plugin hexo-renderer-dartsass

---

source/zh-cn/docs/index.md

docs(zh-cn): update index.md

---

source/_data/themes.yml

For some reason, now.sh is no longer supported by Vercel. mrwillcom.now.sh is now moved to mrwillcom.vercel.app.
Thanks 😊

theme: Update Cupertino

---

source/_posts/2021-07-09-hexo-renderer-pug-2-0-0-hexo-cli-4-3-0-hexo-paginaiton-2-0-0-hexo-clean-css-2-0-0.md

> https://github.com/hexojs/hexo-cli/releases/tag/4.3.0
> https://github.com/hexojs/hexo-renderer-pug/releases/tag/2.0.0
> https://github.com/hexojs/hexo-pagination/releases/tag/v2.0.0
> https://github.com/hexojs/hexo-clean-css/releases/tag/2.0.0
- Languages:

news: release news hexo-cli 4.3.0, hexo-renderer-pug 2.0.0, hexo-paginaiton 2.0.0, hexo-clean-css 2.0.0

---

source/_data/plugins.yml

Using Kroki.io to render 20+ diagrams at compile time.

Add plugin: hexo-filter-kroki

---

source/_data/plugins.yml

chore: add hexo-tag-trello plugin

---

source/_data/plugins.yml
source/docs/one-command-deployment.md
source/ko/docs/one-command-deployment.md
source/pt-br/docs/one-command-deployment.md
source/ru/docs/one-command-deployment.md
source/th/docs/one-command-deployment.md
source/zh-cn/docs/one-command-deployment.md
source/zh-tw/docs/one-command-deployment.md

add `hexo-deployer-rss3` to plugins and one-command-deployment documents

---

source/_data/plugins.yml

Add hexo-tag-mdline plugin

---

source/_data/themes.yml

I have changed my GitHub username, therefore I need to update the repo URL for theme Obsidian.
- Languages:

Changed repo url for theme Obsidian

---

source/_data/plugins.yml

- Languages:
Contribute to Hexo and submit two useful plug-ins developed by individuals: map plug-in and statistical chart plug-in

Update plugins.yml  Contribute to Hexo and submit two useful plug-ins developed by individuals: map plug-in and statistical chart plug-in

---

source/_data/plugins.yml

Add new hexo-filter-link-post plugin

---

source/_data/plugins.yml

Add new hexo-insert-markdown plugin

---

source/_data/plugins.yml

I have created a plugin that could auto submit site URLs to major search engines, including Google, Bing, ShenMa and Baidu, to improve the speed and quality of sites included in search engines.
This PR should include the plugin in the list of published plugins on the Hexo website.
- Languages:

Add news plugins named :  hexo-url-submission

---

source/_data/themes.yml

update particle theme preview url

---

.github/workflows/tester.yml

Fix https://github.com/hexojs/site/pull/1693#issuecomment-916750750

ci: fix pull_request_target

---

source/_data/plugins.yml

Add hexo-blogger-xml

---

.github/dependabot.yml

And add github actions updates

Cleanup dependabot

---

source/_data/plugins.yml

Add plugin: hexo-filter-text-autospace

---

source/ru/docs/asset-folders.md

part of the text has been translated into Russian

---

source/ru/docs/commands.md

Translation into Russian of a part of the text

---

source/ru/docs/data-files.md

fixed inaccuracy

---

source/ru/docs/gitlab-pages.md

typo fixed

---

source/docs/front-matter.md

this commit intended to close hexo/#4663 .
cheers, happy coding :)
- Languages:

Docs: add note on permalink

---

source/ru/docs/migration.md

correction of a typo and change help page wordpress

---

source/ru/docs/github-pages.md

correction and translation of part of the text

---

source/zh-cn/docs/configuration.md

a modest contribution
- Update the translation of `ignore` & make this session’s expression clarity.
- Improve the translation of code annotation.
- Languages:

[Docs] Update zh-CN translation of configuration.md

---

source/ru/docs/index.md

translation of part of the text into Russian

---

source/_data/themes.yml

Update theme mashiro's preview address

---

source/_data/plugins.yml

Add plugin: hexo-plugin-schnack

---

source/docs/github-pages.md

- github now defaults to "main" branch
- update actions/setup-node to v2
- see https://github.com/curbengh/curbengh.github.io for demo
- Languages:

page(gh-pages): user site can now be deployed from any branch

---

source/_data/plugins.yml

Add hexo-link-obsidian Plugin

---

source/docs/one-command-deployment.md

docs: add Layer0 deployment guide

---

source/_data/plugins.yml

Update hexo-bilibili-bangumi description & Delete hexo-online-server

---

source/_data/themes.yml

Fix: preview link has been expired and need to be replaced

---

source/_data/plugins.yml

Add plugin hexo-deployer-firebase

---

source/_data/plugins.yml

- Languages:
I develop a plugin for embedding FB comments plugin. The difference between exists plugin is: this plugin doesn't require any modification of theme! I hope this can help people who use npm installing theme.

plugin: add hexo-tag-fb-comments

---

source/docs/writing.md

Fix the wrong hierarchy in writing.md

---

source/docs/github-pages.md

Add the missing periods to github-pages.md

---

source/_data/plugins.yml

Add new plugin hexo-github-repo-tag

---

source/zh-tw/docs/github-pages.md

Change deployment tutorial from Travis CI to GitHub Actions
- Languages:

Update GitHub pages deployment tutorial for zh-TW

---

source/docs/tag-plugins.md

Fix image name error

---

source/docs/helpers.md
source/ko/docs/helpers.md
source/pt-br/docs/helpers.md
source/ru/docs/helpers.md
source/th/docs/helpers.md
source/zh-cn/docs/helpers.md
source/zh-tw/docs/helpers.md

refs: https://github.com/hexojs/hexo/pull/4871
- Languages:

docs: add data-toc-unnumbered option

---

source/docs/syntax-highlight.md
source/docs/tag-plugins.md
source/ko/docs/syntax-highlight.md
source/ko/docs/tag-plugins.md
source/pt-br/docs/syntax-highlight.md
source/pt-br/docs/tag-plugins.md
source/ru/docs/syntax-highlight.md
source/ru/docs/tag-plugins.md
source/th/docs/syntax-highlight.md
source/th/docs/tag-plugins.md
source/zh-cn/docs/syntax-highlight.md
source/zh-cn/docs/tag-plugins.md
source/zh-tw/docs/syntax-highlight.md
source/zh-tw/docs/tag-plugins.md

refs:  https://github.com/hexojs/hexo/issues/4516
- Languages:

docs: add line_threshold option

---

source/_data/plugins.yml

Add plugin: hexo-readmore

---

source/docs/gitlab-pages.md

- update image to nodejs 16
- update links to gitlab docs
- Languages:

page(gl-pages): use newer .gitlab-ci.yml syntax

---

source/_data/plugins.yml

plugin: hexo-insert-toc

---

source/_data/themes.yml

update hexo-theme-bamboo preview url

---

source/_data/plugins.yml

plugin hexo-absolute

---

source/_data/themes.yml

hexo-theme-white change preview website link

hexo-theme-white change preview website link

---

source/_data/plugins.yml

plugin: hexo-renderer-jsx

---

source/_data/plugins.yml

plugin: hexo-midijs

---

source/_data/themes.yml

theme: modify the description of hexo-theme-particlex

---

source/_data/plugins.yml

(hexo-info-api, hexo-generator-index-custom)
- Languages:

UPLOAD: 新增插件

---

source/_data/plugins.yml

Add new plugin `hexo-bangumis`

---

source/_data/plugins.yml

plugin: `hexo-partytown`

---

source/_data/plugins.yml

plugin:add hexo-minecraft-skin-viewer

---

source/docs/helpers.md
source/zh-cn/docs/helpers.md

ref: hexojs/hexo#5006
- Languages:

feat(helper/is): add is_home_first_page() helper (hexojs/hexo#5006)

---

source/docs/helpers.md
source/zh-cn/docs/helpers.md

ref: hexojs/hexo#5010
- Languages:

feat(helper/toc): more flexible class name (hexojs/hexo#5010)

---

source/_posts/2022-09-09-hexo-6-3-0-released.md

As is the title.
- Languages:
---
Thank you :)

chore(news): hexo 6.3.0 released

---

source/_data/plugins.yml

plugin: hexo-dynamic-config

---

source/_data/themes.yml

theme: update hexo-theme-kira

---

source/_data/plugins.yml

plugin: hexo-indexnow

---

source/docs/troubleshooting.md
source/zh-cn/docs/troubleshooting.md

See https://github.com/hexojs/hexo/issues/4917
- Languages:

Add solution to YAMLExpection

---

source/zh-cn/docs/asset-folders.md

docs(zh-cn): update asset-folders.md

---

source/zh-cn/docs/github-pages.md

docs(zh-cn): update  github-pages.md

---

source/docs/github-pages.md
source/zh-tw/docs/github-pages.md

refs: https://github.com/hexojs/hexo/discussions/5060
- Languages:

docs: update `github-pages` for `git submodule`

---

source/_data/themes.yml

Related to xtexChooser/upptime#4
- Languages:

fix: change the URL for Flavor theme

---

source/_data/plugins.yml

add hexo-obsidian-link plugin

---

.github/PULL_REQUEST_TEMPLATE.md
source/ko/index.pug
source/pt-br/index.pug
source/th/index.pug
themes/navy/source/css/_partial/index.styl

As is the title.
These documents are no longer maintained by native speakers.
- ko: https://github.com/hexojs/site/commits/4cdc461c90b953b3839333be8637a965d66b46fb/source/ko
- pt-br: https://github.com/hexojs/site/commits/4cdc461c90b953b3839333be8637a965d66b46fb/source/pt-br
- th: https://github.com/hexojs/site/commits/4cdc461c90b953b3839333be8637a965d66b46fb/source/th
Maintaining them is very costly for us. I suggest we should give up maintain them.
Add alert message on the top page.
- Languages:

docs: add alert of not maintained message for `ko`, `pt-br`, `th` language documents

---

source/_data/plugins.yml

plugin: `hexo-lightningcss`

---

.github/PULL_REQUEST_TEMPLATE.md

plase → please
- Languages:
> **Note**
>
> **Warning**
>
> `ko`, `pt-br`, `th` languages document are inactive. Plase, submit issue if you want to continuous contribution to them.

fix: typo in pull request template

---

source/zh-cn/api/console.md
source/zh-cn/api/filter.md
source/zh-cn/api/helper.md
source/zh-cn/api/injector.md
source/zh-cn/api/posts.md
source/zh-cn/api/renderer.md
source/zh-cn/api/rendering.md
source/zh-cn/api/tag.md
source/zh-cn/api/themes.md

- Languages:
> **Note**
>
> **Warning**
>
> `ko`, `pt-br`, `th` languages document are inactive. Plase, submit issue if you want to continuous contribution to them.

docs(zh-cn): translate api folder

---

source/zh-cn/docs/helpers.md

- Languages:
> **Note**
>
> **Warning**
>

docs(zh-cn): fix up helpers translation

---

source/zh-cn/api/rendering.md
source/zh-cn/docs/github-pages.md
source/zh-cn/docs/gitlab-pages.md
source/zh-cn/docs/permalinks.md
source/zh-cn/docs/setup.md
source/zh-cn/docs/troubleshooting.md

- Languages:
> **Note**
>
> **Warning**
>

docs(zh-cn): update translation and url

---

source/_data/plugins.yml

I want to publish my plugin on Hexo official website.
I have read the [plugin publishing doc](https://hexo.io/docs/plugins#Publishing).
the name of plugin is unique. And
link URL is correct.

plugin: hexo-tag-graphviz

---

source/_data/themes.yml

- Languages:
> **Note**
>
> **Warning**
>
> `ko`, `pt-br`, `th` languages document are inactive. Plase, submit issue if you want to continuous contribution to them.

Update Stellar's description.

---

source/docs/one-command-deployment.md

Hey, so I created hexo connector with Edgio to ease the deployment process: https://docs.edg.io/guides/changelog#:~:text=%5B5.X%5D%20Add%20Hexo%20Connector%20(With%20Integration%20Tests)%20(%231548)%20%40rishi%2Draj%2Djain
Updated the guide to be even shorter and easier to deploy.

refractor: layer0 to edgio

---

source/_data/themes.yml

- Languages:
> **Note**
>
> **Warning**
>

修改bamboo主题预览地址

---

package.json
source/_data/themes.yml

- Languages:
> **Note**
>
> **Warning**
>

hexo-theme-dimension

---

source/zh-cn/api/index.md
source/zh-cn/docs/github-pages.md
source/zh-cn/docs/troubleshooting.md

- Languages:
> **Note**
>
> **Warning**
>

docs(zh-cn): update translation

---

package.json

chore(deps): update dependenceis

---

source/_posts/2023-03-18-hexo-7-0-0-rc1-released.md

refs:
- https://github.com/hexojs/hexo/releases/tag/v7.0.0-rc1
- https://www.npmjs.com/package/hexo/v/7.0.0-rc1
- Languages:

news: release `v7.0.0-rc1`

---

source/_data/plugins.yml

- Languages:
> **Note**
>
> **Warning**
>

Plugin: hexo-mahgen.

---

source/_data/plugins.yml

- Languages:
> **Note**
>
> **Warning**
>

plugin: add hexo-webp-polyfill

---

.gitignore
.husky/pre-commit
package.json
source/_data/plugins.yml

https://hexo.io/docs/plugins#Publishing
https://github.com/AsemAlhaidary/hexo-generator-readtime/issues/2
- Languages:
> **Note**
>
> **Warning**
>

add `hexo-generator-readtime` plugin

---

source/zh-cn/docs/index.md
source/zh-tw/docs/index.md

The old taobao mirror `npm.taobao.org` has been taken offline. Update it to `npmmirror.com` to fix the problem.
See: https://developer.aliyun.com/mirror/NPM
- Languages:
> **Note**
>
> **Warning**
>

docs(index): update taobao mirror to `npmmirror.com`

---

source/_data/plugins.yml
source/_data/themes.yml

Update links for Hexo-Babel, Hexo-Helper-Crypto and Hexo-Theme-Particlex.
- Languages:
> **Note**
>
> **Warning**
>

docs: update links for 2 plugins and 1 theme

---

source/_data/themes.yml

- Languages:
> **Note**
>
> **Warning**
>

update theme Fan preview link

---

source/_data/themes.yml

- Languages:
> **Note**
>
> **Warning**
>

docs: update link for ShokaX

---

source/_data/plugins.yml

- Languages:
> **Note**
>
> **Warning**
>

add plugin hexo-runcode

---

source/docs/configuration.md

- Languages:
> **Note**
>
> **Warning**
>

clarify how to use category_map and tag_map

---

source/docs/commands.md

Although the documentation explains how to publish a draft, I couldn't find anywhere that explained how to create one. I eventually figured out, but thought it should be added to the documentation as well.
I'm not able to translate this text into any of the other languages. I hope there is a process for that.
- Languages:

Add instructions for creating a draft

---

source/_data/themes/mnh.yml

- [*] I want to publish my theme on Hexo official website.
- [*] I have read the [theme publishing doc](https://hexo.io/docs/themes#Publishing).
- [*] `name` is unique.
- [*] `link` URL is correct.
- [*] `preview` URL is correct.
- [*] `preview` URL web site is rendered correctly.
- [*] Add a screenshot to `source/themes/screenshots`.
- [*] Screenshot filename is same as value of `name`.
- [*] Screenshot size is `800 * 500`.
- [*] Screenshot file format is `png`.
- Languages:
> **Note**
>
> **Warning**
>

Change theme mnh demo address

---

source/_data/plugins/hexo-workbox-build.yml

plugin: add `hexo-workbox-build`

---

scripts/data.js

fix(data): warehouse id error

---

source/_data/plugins/hexo-asset-pro.yml

- Languages:
update the plugin url.
> **Note**
>
> **Warning**
>

update plugin url

---

source/_data/plugins/hexo-swpp.yml

add plugin
> **Note**
>
> **Warning**
>

plugin: Add hexo-swpp plugin

---

source/_data/plugins/hexo-bin-pagination.yml

- Languages:
> **Note**
>
> **Warning**
>

plugins: add hexo-bin-pagination

---

source/_data/plugins/hexo-render-pug.yml

Sorry, I made a mistake in #2069
I accidentally replaced it when I replace other docs url.

fix(plugins): `hexo-render-pug` url

---

README.md

chore: fix badge

---

source/api/helper.md
source/api/rendering.md

- Languages:
https://github.com/hexojs/site/pull/2077#discussion_r1348907453

docs: fix grammatical error

---

.github/labeler.yml
.github/workflows/labeler.yml

A github-action that automatically adds labels to PR
a demo https://github.com/uiolee/site/pull/1

ci: add PR labeler

---

source/_data/plugins/hexo-post-replace

- Languages:
> **Note**
>
> **Warning**
>

Plugin: hexo-post-replace

---

source/docs/helpers.md
source/zh-cn/docs/helpers.md
source/zh-tw/docs/helpers.md

- Languages:
> **Note**
>
> **Warning**
>
related PR
https://github.com/hexojs/hexo/pull/4748

docs(helper): add twitter_image for open_graph

---

source/zh-cn/docs/configuration.md

fix   参数错误
- Languages:
> **Note**
>
> **Warning**
>

docs: fix a error in configuration.md

---

source/about/index.md

- Languages:
> **Note**
>
> **Warning**
>

docs(about): fix gramatical errors 

---

source/_data/plugins/hexo-shiki-plugin.yml

- Languages:
> **Note**
>
> **Warning**
>

plugin: add hexo-shiki-plugin

---

source/_data/plugins/hexo-tag-pcloud.yml

Add a new tag to embed pcloud links to display images.
- Languages:
> **Note**
>
> **Warning**
>

plugin: add plugin hexo-tag-pcloud

---

source/_data/plugins/hexo-auto-backup.yml

- Languages:
> **Note**
>
> **Warning**
>

plugin: add plugin hexo-auto-backup

---

source/_data/plugins/hexo-multiauthor-plugin.yml

Another plugin that I found on Hexo plugin directory "hexo-multiauthor", but that code was depreciated. So, I made a customizable one, will be maintaining for quite few years.
- Languages:

plugin: add hexo-multiauthor-plugin

---

source/_data/themes/Bcxm.yml

- Languages:
> **Note**
>
> **Warning**
>

theme: fix preview url of hexo-theme-bcxm

---

themes/navy/layout/partial/head.njk
themes/navy/source/ads.txt

Remove google ads. IMHO, we should remove google ads from our site.
refs: https://github.com/orgs/hexojs/discussions/5375
* The current active maintainers can't manage it (we don't have a permission)
* I assume google ads's revenue is very few and it not helpful us
* unfriendly to users

chore: remove Google Ads

---

source/_data/themes/A-Quark.yml
source/_data/themes/ARIA.yml
source/_data/themes/Aomori.yml
source/_data/themes/Cafe.yml
source/_data/themes/Candelas.yml
source/_data/themes/Coder.yml
source/_data/themes/Even.yml
source/_data/themes/Gandalfr.yml
source/_data/themes/July.yml
source/_data/themes/Lap.yml
source/_data/themes/Lightx.yml
source/_data/themes/M-Terminal.yml
source/_data/themes/Nothinglin.yml
source/_data/themes/Ochuunn.yml
source/_data/themes/Primer.yml
source/_data/themes/ProWiki.yml
source/_data/themes/blank.yml
source/_data/themes/concise.yml
source/_data/themes/indigo.yml
source/_data/themes/ztopic.yml

- Languages:
> **Note**
>
> **Warning**
>

theme: update preview link

---

source/_data/plugins/hexo-reveal-embed.yml

- Languages:
> **Note**
>
> **Warning**
>

plugin: add hexo-reveal-embed

---

source/_data/plugins/hexo-server-live.yml

- Languages:
> **Note**
>
> **Warning**
>

plugin: add hexo-server-live plugin

---

source/_data/plugins/hexo-tag-ogp-link-preview.yml

- Languages:
> **Note**
>
> **Warning**
>

plugin: add hexo-tag-ogp-link-preview

---

source/_data/plugins/hexo-pagecounter.yml

- Languages:
> **Note**
>
> **Warning**
>

Add plugin hexo-pagecounter

---

source/docs/helpers.md
source/ru/docs/helpers.md
source/zh-cn/docs/helpers.md
source/zh-tw/docs/helpers.md

- Languages:
relative_date
https://github.com/hexojs/hexo/blob/bb489cb303c4b4b2a76873e96ee3d9f38931a084/lib/plugins/helper/date.ts#L53-L57
time_tag
https://github.com/hexojs/hexo/blob/bb489cb303c4b4b2a76873e96ee3d9f38931a084/lib/plugins/helper/date.ts#L59-L62

docs(helper): relative_date and time_tag

---

source/docs/configuration.md
source/docs/setup.md
source/ru/docs/configuration.md
source/ru/docs/setup.md
source/zh-cn/docs/configuration.md
source/zh-cn/docs/setup.md
source/zh-tw/docs/configuration.md
source/zh-tw/docs/setup.md

- Languages:
> **Note**
>
> **Warning**
>

docs: support v7

---

source/docs/one-command-deployment.md
source/ru/docs/one-command-deployment.md
source/zh-cn/docs/one-command-deployment.md
source/zh-tw/docs/one-command-deployment.md

- Languages:
> **Note**
>
> **Warning**
>

docs: add warning to openshift and rss3

---

source/_data/plugins/hexo-blockquote2note.yml

- Languages:
> **Note**
>
> **Warning**
>

plugin: add hexo-blockquote2note

---

source/docs/one-command-deployment.md
source/ja/docs/one-command-deployment.md
source/ko/docs/one-command-deployment.md
source/pt-br/docs/one-command-deployment.md
source/ru/docs/one-command-deployment.md
source/th/docs/one-command-deployment.md
source/zh-cn/docs/one-command-deployment.md
source/zh-tw/docs/one-command-deployment.md

Docs for https://github.com/hexojs/hexo-deployer-ftpsync
> **Note**
>
> **Warning**
>

docs(one-command-deployment): update ftpsync

---

source/ja/docs/one-command-deployment.md

Japanese translation of #2153
- Languages:

docs(one-command-deployment): Japanese translation of #2153

---

themes/navy/source/css/_partial/highlight.styl
themes/navy/source/css/_partial/page.styl
themes/navy/source/css/_partial/sidebar.styl

Honestly, IMHO Hexo's documentation visibilities are low. This PR is part of improve visibility of `hexo.io`.
This PR contains below changes.
* adjust margin and font size of headers (h1 ~ h6)
* adjust footer's margin
* change highlight colors
* adjust side bar margin and font size
Please see below image.
I'm not familiar with website design. Please tell me if my change has some kinds of problems.
-----
Thanks :)

styles: improve documents visibility

---

source/zh-tw/docs/configuration.md

- Languages:
> **Note**
>
> **Warning**
>

docs: fix the anchor link

---

source/zh-tw/docs/asset-folders.md
source/zh-tw/docs/commands.md
source/zh-tw/docs/configuration.md
source/zh-tw/docs/contributing.md
source/zh-tw/docs/index.md

docs(zh-tw): update zh-tw translation

---

source/_data/plugins/hexo-abbrlink3.yml
source/_data/plugins/hexo-encrypted-package-html.yml
source/_data/plugins/hexo-generator-readme.yml
source/_data/plugins/hexo-issue2readme.yml
source/_data/plugins/hexo-obsdian-link-plus.yml

Add plugins.
See https://github.com/hexojs/site/pull/1595 https://github.com/hexojs/site/pull/1596 https://github.com/hexojs/site/pull/1603 https://github.com/hexojs/site/pull/1629 https://github.com/hexojs/site/pull/1975

add plugins

---

source/_data/plugins/hexo-filter-titlebased-link.yml

- Languages:
> **Note**
>
> **Warning**
>

Add a plugin: hexo-filter-titlebased-link

---

source/_data/plugins/hexo-front-matter-defaults.yml

- Languages:
> **Note**
>
> **Warning**
>

chore: add plugin `hexo-front-matter-defaults`

---

source/_data/plugins/hexo-browser-reloader-websocket.yml

chore: add plugin `hexo-browser-reloader-websocket`

---

source/_data/plugins/create-hexo.yml

plugin: add create-hexo

---

source/_data/plugins/hexo-esbuild.yaml
source/_data/plugins/hexo-htmlnano.yml

plugin: add hexo-esbuild, hexo-htmlnano

---

source/_data/themes/Frame.yml

This is just an update to an existing theme:
I updated the url of the demo site.

theme: update theme Frame

---

source/_data/plugins/hexo-markdown-image.yml

- Languages:
> **Note**
>
> **Warning**
>

plugin: add hexo-markdown-image

---

source/_data/plugins/hexo-console-zhihu.yml

- Languages:
> **Note**
>
> **Warning**
>

plugin: add hexo-console-zhihu

---

source/_data/plugins/hexo-daily-news.yml

- Languages:
> **Note**
>
> **Warning**
>

plugin: hexo-daily-news

---

source/_data/plugins/hexo-create-issues.yml

- Languages:
> **Note**
>
> **Warning**
>

plugin: add hexo-create-issues 

---

source/_data/plugins/hexo-generator-plus.yml

- Languages:
> **Note**
>
> **Warning**
>

plugin: add hexo-generator-plus

---

source/_data/plugins/hexo-coliru.yml

- Languages:
> **Note**
>
> **Warning**
>

plugin: add hexo-coliru

---

source/_posts/2024-07-02-hexo-7-3-0-released.md

refs: https://github.com/hexojs/hexo/releases/tag/v7.3.0
- Languages:
> **Note**
>
> **Warning**
>

chore: release news v7.3.0

---

package.json

chore(deps): bump hexo deps

---

.github/workflows/crowdin-pr.yml

#2150 add Japanese translation. But #2146 forgot to add `ja` to crowdin and ci

ci(crowdin): add ja

---

source/docs/helpers.md

b341993b40916f41a1061bbdd0ed8ea05b940aec
https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/css.ts
- Languages:

docs(helpers/css): Remove duplicate text

---

source/_data/plugins/hexo-robots.yml

- Languages:
> **Note**
>
> **Warning**
>

feat(add-plugin): add plugin named 'hexo-robots'

---

source/_data/plugins/hexo-bangumi-gallery.yml

- Languages:
> **Note**
>
> **Warning**
>

add plugin hexo-bangumi-gallery

---

source/_data/plugins/hexo-layout.yml

- Languages:
> **Note**
>
> **Warning**
>

add plugin hexo-layout

---

source/_data/plugins/hexo-tag-swiper.yml

- Languages:
> **Note**
>
> **Warning**
>

feat(add-plugin): add plugin named 'hexo-tag-swiper'

---

source/_data/plugins/hexo-tag-bilibili-card.yml

- Languages:
> **Note**
>
> **Warning**
>

Plugins: Add Plugin hexo-tag-bilibili-card

---

source/_data/plugins/hexo-splide-carousel.yml

- Languages:
> **Note**
>
> **Warning**
>

Plugin: add plugin hexo-splide-carousel

---

source/_data/themes/yun.yml

add a tag for the supported shiki syntax highlight engine

theme yun add shiki tag

---

source/_data/themes/Nexmoe.yml

add a tag for the supported shiki syntax highlight engine

theme Nexmoe add shiki tag

---

source/_data/plugins/hexo-shiki-twoslash.yml

add hexo-shiki-twoslash plugin

---

source/_data/plugins/hexo-zhruby.yml

- Languages:
> **Note**
>
> **Warning**
>

plugin: add hexo-zhruby

---

source/docs/gitlab-pages.md

Fix broken link in gitlab-pages.md

---

source/_data/plugins/hexo-multiple-language-generate.yml

add plugin hexo-multiple-language-generate

---

source/_data/plugins/hexo-graph.yml

- Languages:
Add plugin hexo-graph,A versatile plugin based on ECharts that integrates blog heatmap, monthly statistics chart, category statistics chart, and tag statistics chart.
Here is the repo:
- https://github.com/codepzj/hexo-graph

Add plugin hexo-graph

---

source/_data/themes/Random.yml

theme update Random preview url

---

source/_data/plugins/hexo-filter-custom-link.yml

Add plugin hexo-filter-custom-link

---

source/_data/plugins/hexo-stats-echarts.yml

new plugin: hexo-stats-echarts

---

source/_data/plugins/hexo-d2.yml

feat(plugin): add hexo-d2

---

source/_data/plugins/hexo-everyday-calendar.yml

add a new plugin: hexo-everyday-calendar

---

source/_data/plugins/hexo-everyday-calendar.yml

update hexo-everyday-calendar introduction and tag

---

scripts/helpers.js
source/_data/languages.yml

fix: update language data structure for consistency

---

source/_data/plugins/hexo-font-spider.yml

add hexo-font-spider plugin

---

source/plugins/hexo-bilibili-video-tag.yml

Embeded new BV-based bilibili video in your post.
- Languages:

feat: add plugin: hexo-bilibili-video-tag

---

source/docs/permalinks.md

docs(Permalinks): add `:timestamp`

---

.github/workflows/tester.yml
scripts/validate.js

Issue resolved: https://github.com/hexojs/site/issues/2375

chore: fail the action if validation failed

---

source/_data/plugins/hexo-deployer-walrus.yml

plugin: add hexo-deployer-walrus

---

_config.yml
themes/navy/layout/partial/after_footer.njk
themes/navy/layout/partial/head.njk
themes/navy/layout/partial/header.njk
themes/navy/source/css/_partial/header.styl

feat: Upgrade Algolia docsearch to v3

---

source/_data/plugins/hexo-deployer-s3-plus.yml

add hexo-deployer-s3-plus.yml

---

source/_posts/2025-09-16-hexo-8-0-0-released.md

release news for [v8.0.0](https://github.com/hexojs/hexo/releases/tag/v8.0.0)
- Languages:
---
Thank you :)

chore: release news `v8.0.0`

---

source/_data/plugins/hexo-filter-copywriting.yml

plugin: add hexo-filter-copywriting

---

themes/navy/source/css/_partial/header.styl

The label "lang-select-label" is overlapped by the select tag, which is set to opacity: 0 but still captures the mouse hover. That’s why the CSS :hover on lang-select-label never triggers. I fixed adding two rules to the botton of the css file and the same transition that the rest of the buttons on the nav have.
- Languages:
https://deploy-preview-2418--hexo-site.netlify.app/

fix(header): fix missing hover style on lang-select
